use crate::ast::*;
use std::collections::{BTreeMap, HashSet};

/// Resolve a single call arg to (param_name, ts_type).
/// - "self.field" → look up field type in the role's data type
/// - plain ident  → look up in context input fields
/// - string/number literals → string / number
fn resolve_arg_type(
    arg: &str,
    role_datatype: &str,
    ctx_inputs: &BTreeMap<String, String>,
    data_fields: &BTreeMap<String, BTreeMap<String, String>>,
) -> (String, String) {
    if arg.starts_with("self.") {
        let field = &arg[5..];
        let ty = data_fields
            .get(role_datatype)
            .and_then(|fm| fm.get(field))
            .cloned()
            .unwrap_or_else(|| "any".to_string());
        (field.to_string(), ty)
    } else if arg.starts_with('\'') || arg.starts_with('"') {
        ("value".to_string(), "string".to_string())
    } else if arg.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        ("value".to_string(), "number".to_string())
    } else {
        // plain ident — check context input fields
        let ty = ctx_inputs
            .get(arg)
            .cloned()
            .unwrap_or_else(|| "any".to_string());
        (arg.to_string(), ty)
    }
}

fn rust_type(s: &str) -> String {
    if s.ends_with('?') {
        let inner = rust_type(&s[..s.len() - 1]);
        return format!("Option<{}>", inner);
    }
    if s.starts_with("Lista<") && s.ends_with('>') {
        let inner = &s[6..s.len() - 1];
        return format!("Vec<{}>", rust_type(inner));
    }
    if s == "Lista" {
        return "Vec<String>".to_string();
    }
    match s {
        "Texto"     => "String".to_string(),
        "Numero"    => "i32".to_string(),
        "Booleano"  => "bool".to_string(),
        "Id"        => "String".to_string(),
        "Entero"    => "i32".to_string(),
        "Color"     => "String".to_string(),
        "Timestamp" => "u64".to_string(),
        other       => other.to_string(),
    }
}

fn ts_type(s: &str) -> String {
    // Handle optional suffix (e.g. "Texto?")
    if s.ends_with('?') {
        return ts_type(&s[..s.len() - 1]);
    }
    // Handle Lista<X>
    if s.starts_with("Lista<") && s.ends_with('>') {
        let inner = &s[6..s.len() - 1];
        return format!("{}[]", ts_type(inner));
    }
    // Handle bare Lista (no type param)
    if s == "Lista" {
        return "any[]".to_string();
    }
    match s {
        "Texto"     => "string".to_string(),
        "Numero"    => "number".to_string(),
        "Booleano"  => "boolean".to_string(),
        "Id"        => "string".to_string(),
        "Entero"    => "number".to_string(),
        "Color"     => "string".to_string(),
        "Timestamp" => "number".to_string(),
        other       => other.to_string(),
    }
}

pub fn generate_typescript_wasm(program: &Program) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by Trenza DSL Compiler (Strand 1 - WASM Bridge)\n\n");
    
    // 1. Context Enum
    let mut contexts = Vec::new();
    for def in &program.definitions {
        if let Definition::Context(c) = def {
            contexts.push(c.name.clone());
        }
    }
    
    output.push_str("export enum Contexto {\n");
    for ctx in &contexts {
        output.push_str(&format!("    {} = \"{}\",\n", ctx, ctx));
    }
    output.push_str("}\n\n");

    // 2. Data Interfaces
    for def in &program.definitions {
        if let Definition::Data(d) = def {
            output.push_str(&format!("export interface {} {{\n", d.name));
            for field in &d.fields {
                let optional = field.datatype.ends_with('?');
                let ty = ts_type(&field.datatype);
                if optional {
                    output.push_str(&format!("    {}?: {};\n", field.name, ty));
                } else {
                    output.push_str(&format!("    {}: {};\n", field.name, ty));
                }
            }
            output.push_str("}\n\n");
        }
    }

    // 3. Effects Interface
    let mut unique_functions: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    if let ActionTarget::Call(call) = &action.target {
                        unique_functions.insert(call.function.clone(), call.args.clone());
                    }
                }
            }
            for effect in &ctx.effects {
                unique_functions.insert(effect.call.function.clone(), effect.call.args.clone());
            }
            for fills in &ctx.fills {
                for role in &fills.roles {
                    for action in &role.actions {
                        if let ActionTarget::Call(call) = &action.target {
                            unique_functions.insert(call.function.clone(), call.args.clone());
                        }
                    }
                }
                for effect in &fills.effects {
                    unique_functions.insert(effect.call.function.clone(), effect.call.args.clone());
                }
            }
        }
    }

    output.push_str("export interface Effects {\n");
    for (func, _args) in &unique_functions {
        let func_safe = func.replace(".", "_");
        let arg_list = _args.iter().enumerate().map(|(i, _)| {
            let ty = "any";
            format!("arg{}: {}", i, ty)
        }).collect::<Vec<_>>().join(", ");
        output.push_str(&format!("    {}({}): void;\n", func_safe, arg_list));
    }
    output.push_str("}\n\n");

    // 4. Wasm Bridge Class
    output.push_str("/**\n");
    output.push_str(" * Bridge entre el nucleo WASM de Trenza y el entorno de ejecucion TS.\n");
    output.push_str(" */\n");
    output.push_str("export class TrenzaSystem {\n");
    output.push_str("    private interpreter: any; // Type: InterpreterWasm\n");
    output.push_str("    private effects: Effects;\n\n");
    
    output.push_str("    constructor(interpreter: any, effects: Effects) {\n");
    output.push_str("        this.interpreter = interpreter;\n");
    output.push_str("        this.effects = effects;\n");
    output.push_str("    }\n\n");

    output.push_str("    public get current_state(): Contexto {\n");
    output.push_str("        return this.interpreter.get_state() as Contexto;\n");
    output.push_str("    }\n\n");

    output.push_str("    public get concurrent_states(): Set<Contexto> {\n");
    output.push_str("        return new Set(this.interpreter.get_concurrent_states() as Contexto[]);\n");
    output.push_str("    }\n\n");

    output.push_str("    /**\n");
    output.push_str("     * Despacha un evento al nucleo WASM y ejecuta los efectos resultantes.\n");
    output.push_str("     */\n");
    output.push_str("    public dispatch(event: string, payload: any = {}): void {\n");
    output.push_str("        const resultJson = this.interpreter.dispatch(event, JSON.stringify(payload));\n");
    output.push_str("        const result = JSON.parse(resultJson);\n\n");
    
    output.push_str("        if (result.triggered_effects) {\n");
    output.push_str("            for (const effect of result.triggered_effects) {\n");
    output.push_str("                const funcName = effect.name.replace(/\\./g, '_');\n");
    output.push_str("                if (typeof (this.effects as any)[funcName] === 'function') {\n");
    output.push_str("                    (this.effects as any)[funcName](...effect.args);\n");
    output.push_str("                }\n");
    output.push_str("            }\n");
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output
}

pub fn generate_typescript(program: &Program, _profile: &str, _concurrency: &str) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by Trenza DSL Compiler (Strand 1 - TS)\n\n");
    
    // 1. Context Enum
    let mut contexts = Vec::new();
    for def in &program.definitions {
        if let Definition::Context(c) = def {
            contexts.push(c.name.clone());
        }
    }
    
    output.push_str("export enum Contexto {\n");
    for ctx in &contexts {
        output.push_str(&format!("    {} = \"{}\",\n", ctx, ctx));
    }
    output.push_str("}\n\n");

    // 2. Data Interfaces
    for def in &program.definitions {
        if let Definition::Data(d) = def {
            output.push_str(&format!("export interface {} {{\n", d.name));
            for field in &d.fields {
                let optional = field.datatype.ends_with('?');
                let ty = ts_type(&field.datatype);
                if optional {
                    output.push_str(&format!("    {}?: {};\n", field.name, ty));
                } else {
                    output.push_str(&format!("    {}: {};\n", field.name, ty));
                }
            }
            output.push_str("}\n\n");
        }
    }

    // Build data field map: data_type_name → (field_name → ts_type)
    let mut data_fields: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Data(d) = def {
            let fields: BTreeMap<String, String> = d.fields.iter()
                .map(|f| (f.name.clone(), ts_type(&f.datatype)))
                .collect();
            data_fields.insert(d.name.clone(), fields);
        }
    }

    // Build authoritative external signatures: fn_name → [(param_name, ts_type)]
    let mut external_sigs: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::External(ext) = def {
            for action in &ext.actions {
                let params: Vec<(String, String)> = action.params.iter()
                    .map(|(name, ty)| {
                        let is_opt = ty.ends_with('?');
                        let base_ty = ts_type(ty);
                        let full_ty = if is_opt { format!("{} | undefined", base_ty) } else { base_ty };
                        (name.clone(), full_ty)
                    })
                    .collect();
                external_sigs.insert(action.name.clone(), params);
            }
        }
    }

    // 3. Effects Interface — infer types from call sites, override with external sigs
    // Value: Vec<(param_name, ts_type)>
    let mut unique_functions: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();

    let mut collect_call = |call: &ActionCall, role_datatype: &str, ctx_inputs: &BTreeMap<String, String>| {
        unique_functions.entry(call.function.clone()).or_insert_with(|| {
            call.args.iter()
                .map(|arg| resolve_arg_type(arg, role_datatype, ctx_inputs, &data_fields))
                .collect()
        });
    };

    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            let ctx_inputs: BTreeMap<String, String> = ctx.inputs.iter()
                .map(|f| (f.name.clone(), ts_type(&f.datatype)))
                .collect();
            for role in &ctx.roles {
                for action in &role.actions {
                    if let ActionTarget::Call(call) = &action.target {
                        collect_call(call, &role.datatype, &ctx_inputs);
                    }
                }
            }
            for effect in &ctx.effects {
                collect_call(&effect.call, "", &ctx_inputs);
            }
            for fills in &ctx.fills {
                let fills_inputs: BTreeMap<String, String> = BTreeMap::new();
                for role in &fills.roles {
                    for action in &role.actions {
                        if let ActionTarget::Call(call) = &action.target {
                            collect_call(call, &role.datatype, &fills_inputs);
                        }
                    }
                }
                for effect in &fills.effects {
                    collect_call(&effect.call, "", &fills_inputs);
                }
            }
        }
    }

    // Override inferred sigs with authoritative external definitions
    for (name, params) in &external_sigs {
        unique_functions.insert(name.clone(), params.clone());
    }

    output.push_str("export interface Effects {\n");
    for (func, params) in &unique_functions {
        let func_safe = func.replace(".", "_");
        let arg_list = params.iter().enumerate()
            .map(|(i, (name, ty))| {
                let param_name = if name == "value" || name.is_empty() {
                    format!("arg{}", i)
                } else {
                    name.clone()
                };
                format!("{}: {}", param_name, ty)
            })
            .collect::<Vec<_>>()
            .join(", ");
        output.push_str(&format!("    {}({}): void;\n", func_safe, arg_list));
    }
    output.push_str("}\n\n");

    // 4. System Class
    let mut initial_state = "Unknown".to_string();
    let mut concurrent_contexts = Vec::new();
    let mut overlay_set: HashSet<String> = HashSet::new();
    for def in &program.definitions {
        if let Definition::System(sys) = def {
            initial_state = sys.initial.clone();
            for sec in &sys.sections {
                match sec {
                    SystemSection::Concurrent(ctxs) => concurrent_contexts = ctxs.clone(),
                    SystemSection::Overlays(ctxs) => overlay_set.extend(ctxs.iter().cloned()),
                    _ => {}
                }
            }
        }
    }

    output.push_str("export class System {\n");
    output.push_str("    public state: Contexto;\n");
    output.push_str("    public concurrent_states: Set<Contexto> = new Set();\n");
    output.push_str("    private stateStack: Contexto[] = [];\n");
    output.push_str("    private effects: Effects;\n\n");

    output.push_str("    constructor(initial: Contexto, effects: Effects) {\n");
    output.push_str("        this.state = initial;\n");
    output.push_str("        this.effects = effects;\n");
    output.push_str("    }\n\n");

    output.push_str("    public handleEvent(event: string): void {\n");
    output.push_str("        switch (this.state) {\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            if concurrent_contexts.contains(&ctx.name) { continue; }
            output.push_str(&format!("            case Contexto.{}:\n", ctx.name));
            for trans in &ctx.transitions {
                output.push_str(&format!("                if (event === \"{}\") {{\n", trans.event));
                match trans.target.as_str() {
                    "[stay]" => {
                        output.push_str("                    return;\n");
                    },
                    "[close_overlay]" => {
                        output.push_str(&format!(
                            "                    this.state = this.stateStack.pop() ?? Contexto.{};\n",
                            initial_state
                        ));
                        output.push_str("                    return;\n");
                    },
                    target => {
                        if overlay_set.contains(target) {
                            output.push_str("                    this.stateStack.push(this.state);\n");
                        }
                        output.push_str(&format!("                    this.state = Contexto.{};\n", target));
                        output.push_str("                    return;\n");
                    }
                }
                output.push_str("                }\n");
            }
            output.push_str("                break;\n");
        }
    }
    output.push_str("        }\n");
    output.push_str("    }\n\n");

    output.push_str("    public activateConcurrent(ctx: Contexto): void {\n");
    output.push_str("        this.concurrent_states.add(ctx);\n");
    output.push_str("    }\n\n");

    output.push_str("    public deactivateConcurrent(ctx: Contexto): void {\n");
    output.push_str("        this.concurrent_states.delete(ctx);\n");
    output.push_str("    }\n\n");

    // 5. Role/Event Handlers — computed before closing the class so dispatch_* methods
    //    can be added as System members.
    let mut grouped_actions: BTreeMap<(String, String), Vec<(String, RoleAction)>> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    let key = (role.name.clone(), action.event.clone());
                    grouped_actions.entry(key).or_default().push((ctx.name.clone(), action.clone()));
                }
            }
            for fills in &ctx.fills {
                for role in &fills.roles {
                    for action in &role.actions {
                        let key = (role.name.clone(), action.event.clone());
                        grouped_actions.entry(key).or_default().push((fills.target_context.clone(), action.clone()));
                    }
                }
            }
        }
    }

    // Precompute role → ts_type map
    let mut role_types: BTreeMap<String, String> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                role_types.entry(role.name.clone()).or_insert_with(|| ts_type(&role.datatype));
            }
            for fills in &ctx.fills {
                for role in &fills.roles {
                    role_types.entry(role.name.clone()).or_insert_with(|| ts_type(&role.datatype));
                }
            }
        }
    }

    // dispatch_* methods — combine effect call + state transition in one call
    for ((role_name, event_name), _) in &grouped_actions {
        let role_type = role_types.get(role_name).map(|s| s.as_str()).unwrap_or("any");
        let safe_event = event_name.replace(".", "_");
        output.push_str(&format!(
            "    public dispatch_{role_name}_{safe_event}({role_name}: {role_type}): void {{\n"
        ));
        output.push_str(&format!(
            "        const event = handle_{role_name}_{safe_event}(this.state, {role_name}, this.effects);\n"
        ));
        output.push_str("        if (event !== null) this.handleEvent(event);\n");
        output.push_str("    }\n\n");
    }

    output.push_str("}\n\n");

    let is_pre = _profile == "pre";

    // Standalone handlers — return the dispatched event name (or null for ignored actions)
    for ((role_name, event_name), handlers) in &grouped_actions {
        let role_type = role_types.get(role_name).map(|s| s.as_str()).unwrap_or("any");
        let safe_event = event_name.replace(".", "_");

        output.push_str(&format!(
            "export function handle_{role_name}_{safe_event}(ctx: Contexto, {role_name}: {role_type}, effects: Effects): string | null {{\n"
        ));
        output.push_str("    switch (ctx) {\n");
        for (ctx_name, action) in handlers {
            output.push_str(&format!("        case Contexto.{}:\n", ctx_name));
            if is_pre {
                output.push_str(&format!("            console.log(`[telemetry] context=${{ctx}}, role={role_name}, event={event_name}`);\n"));
            }
            match &action.target {
                ActionTarget::Call(call) => {
                    let mut args = Vec::new();
                    for arg in &call.args {
                        if arg == "self" {
                            args.push(role_name.clone());
                        } else if arg.starts_with("self.") {
                            args.push(format!("{}.{}", role_name, &arg[5..]));
                        } else {
                            args.push(format!("\"{}\"", arg));
                        }
                    }
                    let func_safe = call.function.replace(".", "_");
                    output.push_str(&format!("            effects.{func_safe}({});\n", args.join(", ")));
                    output.push_str(&format!("            return \"{func_safe}\";\n"));
                },
                ActionTarget::Ignored => {
                    output.push_str("            return null; // ignored\n");
                },
                ActionTarget::Forbidden => {
                    output.push_str(&format!("            throw new Error(`Forbidden action called in context ${{ctx}}`);\n"));
                }
            }
        }
        output.push_str("    }\n");
        output.push_str("    return null;\n");
        output.push_str("}\n\n");
    }

    output
}

pub fn generate_rust(program: &Program, profile: &str, concurrency: &str) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by Trenza DSL Compiler\n");
    output.push_str(&format!("// Compiler Profile: {}\n", profile));
    output.push_str(&format!("// Concurrency Mode: {}\n\n", concurrency));
    
    // 1. Context Enum
    let mut contexts = Vec::new();
    let mut concurrent_contexts = Vec::new();
    let mut initial_state = "Unknown".to_string();

    for def in &program.definitions {
        if let Definition::Context(c) = def {
            contexts.push(c.name.clone());
        }
        if let Definition::System(sys) = def {
            initial_state = sys.initial.clone();
            for sec in &sys.sections {
                if let SystemSection::Concurrent(ctxs) = sec {
                    concurrent_contexts = ctxs.clone();
                }
            }
        }
    }

    output.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    output.push_str("pub enum Contexto {\n");
    for ctx in &contexts {
        output.push_str(&format!("    {},\n", ctx));
    }
    output.push_str("}\n\n");

    // 2. Data Structures (Strand 1)
    for def in &program.definitions {
        if let Definition::Data(d) = def {
            output.push_str(&format!("#[allow(non_snake_case)]\n#[derive(Debug, Clone, Default)]\npub struct {} {{\n", d.name));
            for field in &d.fields {
                output.push_str(&format!("    pub {}: {},\n", field.name, rust_type(&field.datatype)));
            }
            output.push_str("}\n\n");
        }
    }

    let is_pre = profile == "pre";
    let use_threads = concurrency == "threads";

    // 3. Effects Trait (Strand 2 Preparation)
    let mut unique_functions: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    if let ActionTarget::Call(call) = &action.target {
                        unique_functions.insert(call.function.clone(), call.args.clone());
                    }
                }
            }
            for effect in &ctx.effects {
                unique_functions.insert(effect.call.function.clone(), effect.call.args.clone());
            }
            for fills in &ctx.fills {
                for role in &fills.roles {
                    for action in &role.actions {
                        if let ActionTarget::Call(call) = &action.target {
                            unique_functions.insert(call.function.clone(), call.args.clone());
                        }
                    }
                }
                for effect in &fills.effects {
                    unique_functions.insert(effect.call.function.clone(), effect.call.args.clone());
                }
            }
        }
    }

    output.push_str("pub trait Effects {\n");
    for (func, args) in &unique_functions {
        let func_safe = func.replace(".", "_");
        let arg_list = args.iter().enumerate().map(|(i, _)| format!("arg{}: &str", i)).collect::<Vec<_>>().join(", ");
        output.push_str(&format!("    fn {}(&self, {});\n", func_safe, arg_list));
    }
    output.push_str("}\n\n");

    output.push_str("pub struct NoOpEffects;\n");
    output.push_str("impl Effects for NoOpEffects {\n");
    for (func, args) in &unique_functions {
        let func_safe = func.replace(".", "_");
        let arg_list = args.iter().enumerate().map(|(i, _)| format!("arg{}: &str", i)).collect::<Vec<_>>().join(", ");
        output.push_str(&format!("    fn {}(&self, {}) {{}}\n", func_safe, arg_list));
    }
    output.push_str("}\n\n");

    output.push_str("pub struct RecordingEffects {\n");
    output.push_str("    pub calls: std::cell::RefCell<Vec<String>>,\n");
    output.push_str("}\n");
    output.push_str("impl RecordingEffects {\n");
    output.push_str("    pub fn new() -> Self {\n");
    output.push_str("        Self { calls: std::cell::RefCell::new(Vec::new()) }\n");
    output.push_str("    }\n");
    output.push_str("    pub fn was_called(&self, func: &str) -> bool {\n");
    output.push_str("        self.calls.borrow().iter().any(|c| c.starts_with(func))\n");
    output.push_str("    }\n");
    output.push_str("}\n");
    output.push_str("impl Effects for RecordingEffects {\n");
    for (func, args) in &unique_functions {
        let func_safe = func.replace(".", "_");
        let arg_list = args.iter().enumerate().map(|(i, _)| format!("arg{}: &str", i)).collect::<Vec<_>>().join(", ");
        let format_args = args.iter().enumerate().map(|_| format!("{{}}")).collect::<Vec<_>>().join(", ");
        let format_values = args.iter().enumerate().map(|(i, _)| format!("arg{}", i)).collect::<Vec<_>>().join(", ");
        
        output.push_str(&format!("    fn {}(&self, {}) {{\n", func_safe, arg_list));
        if args.is_empty() {
            output.push_str(&format!("        self.calls.borrow_mut().push(\"{}\".to_string());\n", func));
        } else {
            output.push_str(&format!("        self.calls.borrow_mut().push(format!(\"{}({})\".to_string(), {}));\n", func, format_args, format_values));
        }
        output.push_str("    }\n");
    }
    output.push_str("}\n\n");

    // 4. System Structure and Transition Logic
    if use_threads {
        output.push_str("use std::sync::mpsc;\nuse std::thread;\nuse std::collections::HashMap;\n\n");
        output.push_str("pub struct System<'a> {\n");
        output.push_str("    pub state: Contexto,\n");
        output.push_str("    pub concurrent_txs: HashMap<Contexto, mpsc::Sender<String>>,\n");
        output.push_str("    pub effects: &'a dyn Effects,\n");
        output.push_str("}\n\n");
    } else {
        output.push_str("use std::collections::HashSet as StdHashSet;\n\n");
        output.push_str("pub struct System<'a> {\n");
        output.push_str("    pub state: Contexto,\n");
        output.push_str("    pub concurrent_states: StdHashSet<Contexto>,\n");
        output.push_str("    pub effects: &'a dyn Effects,\n");
        output.push_str("}\n\n");
    }

    output.push_str("impl<'a> System<'a> {\n");
    output.push_str("    pub fn new(initial: Contexto, effects: &'a dyn Effects) -> Self {\n");
    
    if use_threads {
        output.push_str("        let mut concurrent_txs = HashMap::new();\n");
        for cctx in &concurrent_contexts {
            output.push_str(&format!("        // Spawn thread for concurrent context {}\n", cctx));
            output.push_str(&format!("        let (tx_{}, rx_{}) = mpsc::channel::<String>();\n", cctx, cctx));
            output.push_str(&format!("        thread::spawn(move || {{\n"));
            output.push_str(&format!("            let mut local_state = Contexto::{};\n", cctx));
            output.push_str(&format!("            while let Ok(msg) = rx_{}.recv() {{\n", cctx));
            output.push_str(&format!("                if msg == \"TERMINATE\" {{ break; }}\n"));
            output.push_str(&format!("            }}\n"));
            output.push_str(&format!("        }});\n"));
            output.push_str(&format!("        concurrent_txs.insert(Contexto::{}, tx_{});\n", cctx, cctx));
        }
        output.push_str("        Self { state: initial, concurrent_txs, effects }\n");
    } else {
        output.push_str("        let mut concurrent_states = StdHashSet::new();\n");
        for cctx in &concurrent_contexts {
            output.push_str(&format!("        concurrent_states.insert(Contexto::{});\n", cctx));
        }
        output.push_str("        Self { state: initial, concurrent_states, effects }\n");
    }
    
    output.push_str("    }\n\n");

    output.push_str("    pub fn handle_event(&mut self, event: &str) {\n");
    
    if use_threads {
        output.push_str("        // Dispatch to concurrent threads\n");
        output.push_str("        for tx in self.concurrent_txs.values() {\n");
        output.push_str("            let _ = tx.send(event.to_string());\n");
        output.push_str("        }\n");
    } else {
        output.push_str("        // Evaluate concurrent states sequentially (Composite Mode)\n");
        for cctx in &concurrent_contexts {
            output.push_str(&format!("        if self.concurrent_states.contains(&Contexto::{}) {{\n", cctx));
            output.push_str(&format!("            // In a full composite synthesis, we evaluate {} logic here\n", cctx));
            output.push_str("        }\n");
        }
    }

    output.push_str("\n        // Evaluate main state\n");
    output.push_str("        match self.state {\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            output.push_str(&format!("            Contexto::{} => {{\n", ctx.name));
            output.push_str("                match event {\n");
            for trans in &ctx.transitions {
                match trans.target.as_str() {
                    "[stay]" => {
                        output.push_str(&format!("                    \"{}\" => {{}},\n", trans.event));
                    },
                    "[close_overlay]" => {
                        output.push_str(&format!("                    \"{}\" => self.state = Contexto::{},\n", trans.event, initial_state));
                    },
                    "[deactivate]" => {
                        if use_threads {
                            output.push_str(&format!("                    \"{}\" => {{ let _ = self.concurrent_txs.get(&Contexto::{}).map(|tx| tx.send(\"TERMINATE\".to_string())); }},\n", trans.event, ctx.name));
                        } else {
                            output.push_str(&format!("                    \"{}\" => {{ self.concurrent_states.remove(&Contexto::{}); }},\n", trans.event, ctx.name));
                        }
                    },
                    target => {
                        output.push_str(&format!("                    \"{}\" => self.state = Contexto::{},\n", trans.event, target));
                    }
                }
            }
            output.push_str("                    _ => {},\n");
            output.push_str("                }\n");
            output.push_str("            },\n");
        }
    }
    output.push_str("        }\n");

    // Side effects on transitions (Lifecycle entry)
    output.push_str("\n        // Evaluate on_entry effects\n");
    output.push_str("        match self.state {\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            let entry_effects: Vec<_> = ctx.effects.iter()
                .filter(|e| matches!(e.trigger, EffectTrigger::Lifecycle(ref s) if s == "on_entry"))
                .collect();
            
            if !entry_effects.is_empty() {
                output.push_str(&format!("            Contexto::{} => {{\n", ctx.name));
                for effect in entry_effects {
                    let mut args = Vec::new();
                    for arg in &effect.call.args {
                        // Lifecycle effects usually take inputs or literals
                        args.push(format!("\"{}\"", arg)); 
                    }
                    output.push_str(&format!("                self.effects.{}({});\n", effect.call.function.replace(".", "_"), args.join(", ")));
                }
                output.push_str("            },\n");
            }
        }
    }
    output.push_str("            _ => {},\n");
    output.push_str("        }\n");

    output.push_str("    }\n");
    output.push_str("}\n\n");

    // 5. Role/Event Handlers (Strand 1)
    let mut grouped_actions: BTreeMap<(String, String), Vec<(String, RoleAction)>> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    let key = (role.name.clone(), action.event.clone());
                    grouped_actions.entry(key).or_default().push((ctx.name.clone(), action.clone()));
                }
            }
            // Include roles from fills
            for fills in &ctx.fills {
                for role in &fills.roles {
                    for action in &role.actions {
                        let key = (role.name.clone(), action.event.clone());
                        grouped_actions.entry(key).or_default().push((fills.target_context.clone(), action.clone()));
                    }
                }
            }
        }
    }

    for ((role_name, event_name), handlers) in grouped_actions {
        // Encontrar el tipo de dato del rol (asumimos consistencia por Regla 8)
        let mut role_type = "String".to_string();
        'find_role: for def in &program.definitions {
            if let Definition::Context(ctx) = def {
                for role in &ctx.roles {
                    if role.name == role_name { 
                        role_type = role.datatype.clone(); 
                        break 'find_role; 
                    }
                }
                for fills in &ctx.fills {
                    for role in &fills.roles {
                        if role.name == role_name { 
                            role_type = role.datatype.clone(); 
                            break 'find_role; 
                        }
                    }
                }
            }
        }

        output.push_str(&format!("pub fn handle_{}_{}(ctx: &Contexto, {}: &{}, effects: &dyn Effects) {{\n", role_name, event_name.replace(".", "_"), role_name, role_type));
        output.push_str("    match ctx {\n");
        for (ctx_name, action) in handlers {
            output.push_str(&format!("        Contexto::{} => {{\n", ctx_name));
            if is_pre {
                output.push_str(&format!("            println!(\"[telemetry] context={}, role={}, event={}\");\n", ctx_name, role_name, event_name));
            }
            match &action.target {
                ActionTarget::Call(call) => {
                    let mut args = Vec::new();
                    for arg in &call.args {
                        if arg == "self" {
                            args.push(format!("{}", role_name));
                        } else if arg.starts_with("self.") {
                            args.push(format!("&{}.{}", role_name, arg.replace("self.", "")));
                        } else {
                            args.push(format!("\"{}\"", arg));
                        }
                    }
                    output.push_str(&format!("            effects.{}({});\n", call.function.replace(".", "_"), args.join(", ")));
                },
                ActionTarget::Ignored => {
                    output.push_str("            // ignored\n");
                },
                ActionTarget::Forbidden => {
                    output.push_str(&format!("            panic!(\"Forbidden action called in context {}\");\n", ctx_name));
                }
            }
            output.push_str("        },\n");
        }
        output.push_str("        _ => {},\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");
    }

    output
}

pub fn generate_tests_ts(program: &Program) -> String {
    let mut out = String::new();
    let meta = extract_system_metadata(program);

    // Collect overlay set
    let mut overlay_set: HashSet<String> = HashSet::new();
    for def in &program.definitions {
        if let Definition::System(sys) = def {
            for sec in &sys.sections {
                if let SystemSection::Overlays(ctxs) = sec {
                    overlay_set.extend(ctxs.iter().cloned());
                }
            }
        }
    }

    // Collect all unique effect function signatures
    let mut effect_fns: BTreeMap<String, usize> = BTreeMap::new(); // fn_name -> arg count
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    if let ActionTarget::Call(call) = &action.target {
                        effect_fns.insert(call.function.replace(".", "_"), call.args.len());
                    }
                }
            }
            for effect in &ctx.effects {
                effect_fns.insert(effect.call.function.replace(".", "_"), effect.call.args.len());
            }
            for fills in &ctx.fills {
                for role in &fills.roles {
                    for action in &role.actions {
                        if let ActionTarget::Call(call) = &action.target {
                            effect_fns.insert(call.function.replace(".", "_"), call.args.len());
                        }
                    }
                }
            }
        }
        if let Definition::External(ext) = def {
            for action in &ext.actions {
                effect_fns.insert(action.name.replace(".", "_"), action.params.len());
            }
        }
    }

    // Collect all context names for import
    let mut all_handler_names: Vec<String> = Vec::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    let name = format!("handle_{}_{}", role.name, action.event.replace(".", "_"));
                    if !all_handler_names.contains(&name) {
                        all_handler_names.push(name);
                    }
                }
            }
            for fills in &ctx.fills {
                for role in &fills.roles {
                    for action in &role.actions {
                        let name = format!("handle_{}_{}", role.name, action.event.replace(".", "_"));
                        if !all_handler_names.contains(&name) {
                            all_handler_names.push(name);
                        }
                    }
                }
            }
        }
    }

    // Determine system name for import path
    let mut system_name = "project".to_string();
    for def in &program.definitions {
        if let Definition::System(sys) = def { system_name = sys.name.clone(); break; }
    }

    // ── Header ────────────────────────────────────────────────────────────────
    out.push_str("// Auto-generated algebraic tests by Trenza DSL Compiler (Strand 2 - TS)\n");
    out.push_str("// DO NOT EDIT — regenerate from .trz source\n");
    out.push_str("// Run with: npx vitest\n\n");
    out.push_str("import { describe, it, expect, vi } from 'vitest';\n");
    out.push_str(&format!("import {{ Contexto, System }} from './{system_name}_out';\n"));
    out.push_str(&format!("import type {{ Effects }} from './{system_name}_out';\n"));
    if !all_handler_names.is_empty() {
        let imports = all_handler_names.join(", ");
        out.push_str(&format!("import {{ {imports} }} from './{system_name}_out';\n"));
    }
    out.push_str("\n");

    // ── noOpEffects ────────────────────────────────────────────────────────────
    out.push_str("const noOpEffects: Effects = {\n");
    for (func, _) in &effect_fns {
        out.push_str(&format!("    {func}: () => {{}},\n"));
    }
    out.push_str("};\n\n");

    // ── mockEffects ────────────────────────────────────────────────────────────
    out.push_str("function mockEffects(): Effects {\n");
    out.push_str("    return {\n");
    for (func, _) in &effect_fns {
        out.push_str(&format!("        {func}: vi.fn(),\n"));
    }
    out.push_str("    } as unknown as Effects;\n");
    out.push_str("}\n\n");

    // ── Phase 1: Transition Tests ──────────────────────────────────────────────
    out.push_str("describe('Transitions', () => {\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            if meta.concurrent_contexts.contains(&ctx.name) { continue; }
            for trans in &ctx.transitions {
                let target_assertion = match trans.target.as_str() {
                    "[stay]" => format!("expect(sys.state).toBe(Contexto.{});", ctx.name),
                    "[close_overlay]" => format!("expect(sys.state).toBe(Contexto.{});", meta.initial),
                    "[deactivate]" => format!("expect(sys.concurrent_states.has(Contexto.{})).toBe(false);", ctx.name),
                    t => format!("expect(sys.state).toBe(Contexto.{t});"),
                };
                out.push_str(&format!(
                    "    it('{} on {} → {}', () => {{\n",
                    ctx.name, trans.event, trans.target
                ));
                out.push_str(&format!(
                    "        const sys = new System(Contexto.{}, noOpEffects);\n",
                    ctx.name
                ));
                out.push_str(&format!("        sys.handleEvent('{}');\n", trans.event));
                out.push_str(&format!("        {target_assertion}\n"));
                out.push_str("    });\n\n");
            }
        }
    }
    out.push_str("});\n\n");

    // ── Phase 2: Overlay Stack Tests ───────────────────────────────────────────
    // For each context that has transitions TO overlays AND the overlay has [close_overlay]
    out.push_str("describe('Overlay Stack', () => {\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            if meta.concurrent_contexts.contains(&ctx.name) { continue; }
            for trans in &ctx.transitions {
                if !overlay_set.contains(&trans.target) { continue; }
                // Find a [close_overlay] transition in the target overlay context
                let close_event = program.definitions.iter().find_map(|d| {
                    if let Definition::Context(oc) = d {
                        if oc.name == trans.target {
                            return oc.transitions.iter()
                                .find(|t| t.target == "[close_overlay]")
                                .map(|t| t.event.clone());
                        }
                    }
                    None
                });
                if let Some(close_ev) = close_event {
                    out.push_str(&format!(
                        "    it('opens {} from {} and returns on {}', () => {{\n",
                        trans.target, ctx.name, close_ev
                    ));
                    out.push_str(&format!(
                        "        const sys = new System(Contexto.{}, noOpEffects);\n",
                        ctx.name
                    ));
                    out.push_str(&format!("        sys.handleEvent('{}'); // open overlay\n", trans.event));
                    out.push_str(&format!("        expect(sys.state).toBe(Contexto.{});\n", trans.target));
                    out.push_str(&format!("        sys.handleEvent('{}'); // close overlay\n", close_ev));
                    out.push_str(&format!("        expect(sys.state).toBe(Contexto.{}); // restored\n", ctx.name));
                    out.push_str("    });\n\n");
                }
            }
        }
    }
    out.push_str("});\n\n");

    // ── Phase 3: Handler Tests ─────────────────────────────────────────────────
    out.push_str("describe('Handlers', () => {\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                let role_type = ts_type(&role.datatype);
                for action in &role.actions {
                    let safe_event = action.event.replace(".", "_");
                    let handler = format!("handle_{}_{}", role.name, safe_event);
                    match &action.target {
                        ActionTarget::Forbidden => {
                            out.push_str(&format!(
                                "    it('{} {} {} throws Forbidden', () => {{\n",
                                ctx.name, role.name, safe_event
                            ));
                            out.push_str("        const effects = mockEffects();\n");
                            out.push_str(&format!(
                                "        expect(() => {handler}(Contexto.{}, {{}} as {role_type}, effects)).toThrow('Forbidden');\n",
                                ctx.name
                            ));
                            out.push_str("    });\n\n");
                        },
                        ActionTarget::Ignored => {
                            out.push_str(&format!(
                                "    it('{} {} {} returns null (ignored)', () => {{\n",
                                ctx.name, role.name, safe_event
                            ));
                            out.push_str("        const effects = mockEffects();\n");
                            out.push_str(&format!(
                                "        const event = {handler}(Contexto.{}, {{}} as {role_type}, effects);\n",
                                ctx.name
                            ));
                            out.push_str("        expect(event).toBeNull();\n");
                            out.push_str("    });\n\n");
                        },
                        ActionTarget::Call(call) => {
                            let func_safe = call.function.replace(".", "_");
                            out.push_str(&format!(
                                "    it('{} {} {} invokes {func_safe} and returns event', () => {{\n",
                                ctx.name, role.name, safe_event
                            ));
                            out.push_str("        const effects = mockEffects();\n");
                            out.push_str(&format!(
                                "        const event = {handler}(Contexto.{}, {{}} as {role_type}, effects);\n",
                                ctx.name
                            ));
                            out.push_str(&format!("        expect(event).toBe('{func_safe}');\n"));
                            out.push_str(&format!("        expect((effects as any).{func_safe}).toHaveBeenCalled();\n"));
                            out.push_str("    });\n\n");
                        }
                    }
                }
            }
        }
    }
    out.push_str("});\n\n");

    // ── Phase 4: Exhaustiveness ────────────────────────────────────────────────
    let ctx_count = program.definitions.iter().filter(|d| matches!(d, Definition::Context(_))).count();
    out.push_str("describe('Exhaustiveness', () => {\n");
    out.push_str("    it('Contexto enum has all contexts', () => {\n");
    out.push_str(&format!("        expect(Object.keys(Contexto).length).toBe({ctx_count});\n"));
    out.push_str("    });\n");
    out.push_str("});\n");

    out
}

pub fn generate_tests(program: &Program) -> String {
    let mut output = String::new();
    let metadata = extract_system_metadata(program);

    output.push_str("// Auto-generated algebraic tests by Trenza DSL Compiler (Strand 2)\n");
    output.push_str("// DO NOT EDIT — regenerate from .trz source\n\n");
    output.push_str("#[cfg(test)]\nmod algebraic_tests {\n");
    output.push_str("    use super::*;\n\n");

    // Phase 1: Transition Tests
    generate_transition_tests(program, &metadata, &mut output);

    // Phase 2: Handler Tests
    generate_handler_tests(program, &metadata, &mut output);

    // Phase 3: Exhaustiveness Test
    generate_exhaustiveness_test(program, &mut output);

    // Phase 4: On-entry Tests
    generate_on_entry_tests(program, &metadata, &mut output);

    // Phase 5: Slot/Fills Tests
    generate_fills_tests(program, &metadata, &mut output);

    output.push_str("}\n");
    output
}

struct SystemMetadata {
    initial: String,
    concurrent_contexts: HashSet<String>,
}

fn extract_system_metadata(program: &Program) -> SystemMetadata {
    let mut initial = String::new();
    let mut concurrent_contexts = HashSet::new();

    for def in &program.definitions {
        if let Definition::System(sys) = def {
            initial = sys.initial.clone();
            for sec in &sys.sections {
                if let SystemSection::Concurrent(ctxs) = sec {
                    for ctx in ctxs {
                        concurrent_contexts.insert(ctx.clone());
                    }
                }
            }
        }
    }
    SystemMetadata { initial, concurrent_contexts }
}

fn generate_transition_tests(program: &Program, meta: &SystemMetadata, out: &mut String) {
    out.push_str("    // === Transition Tests ===\n\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                let event_safe = trans.event.replace(".", "_");
                let test_name = format!("test_transition_{}_on_{}", ctx.name, event_safe);

                out.push_str("    #[test]\n");
                out.push_str(&format!("    fn {}() {{\n", test_name));
                out.push_str("        let effects = NoOpEffects;\n");

                if meta.concurrent_contexts.contains(&ctx.name) {
                    out.push_str(&format!("        let mut sys = System::new(Contexto::{}, &effects);\n", meta.initial));
                    // Concurrent contexts are activated by default in System::new currently
                } else {
                    out.push_str(&format!("        let mut sys = System::new(Contexto::{}, &effects);\n", ctx.name));
                }

                out.push_str(&format!("        sys.handle_event(\"{}\");\n", trans.event));

                let target = &trans.target;
                if target == "[stay]" {
                    out.push_str(&format!("        assert_eq!(sys.state, Contexto::{});\n", ctx.name));
                } else if target == "[cerrar_overlay]" {
                    out.push_str(&format!("        assert_eq!(sys.state, Contexto::{});\n", meta.initial));
                } else if target == "[deactivate]" {
                    out.push_str(&format!("        // In threads mode this might differ, but for composite:\n"));
                    out.push_str(&format!("        assert!(!sys.concurrent_states.contains(&Contexto::{}));\n", ctx.name));
                } else {
                    out.push_str(&format!("        assert_eq!(sys.state, Contexto::{});\n", target));
                }
                out.push_str("    }\n\n");
            }
        }
    }
}

fn generate_handler_tests(program: &Program, _meta: &SystemMetadata, out: &mut String) {
    out.push_str("    // === Handler Tests ===\n\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                let role_type = &role.datatype;
                for action in &role.actions {
                    let event_safe = action.event.replace(".", "_");
                    match &action.target {
                        ActionTarget::Forbidden => {
                            out.push_str("    #[test]\n");
                            out.push_str("    #[should_panic(expected = \"Forbidden\")]\n");
                            out.push_str(&format!("    fn test_forbidden_{}_{}_on_{}() {{\n", ctx.name, role.name, event_safe));
                            out.push_str("        let effects = NoOpEffects;\n");
                            out.push_str(&format!("        let data = {}::default();\n", role_type));
                            out.push_str(&format!("        handle_{}_{}(&Contexto::{}, &data, &effects);\n", role.name, event_safe, ctx.name));
                            out.push_str("    }\n\n");
                        },
                        ActionTarget::Ignored => {
                            out.push_str("    #[test]\n");
                            out.push_str(&format!("    fn test_ignored_{}_{}_on_{}() {{\n", ctx.name, role.name, event_safe));
                            out.push_str("        let effects = RecordingEffects::new();\n");
                            out.push_str(&format!("        let data = {}::default();\n", role_type));
                            out.push_str(&format!("        handle_{}_{}(&Contexto::{}, &data, &effects);\n", role.name, event_safe, ctx.name));
                            out.push_str("        assert!(effects.calls.borrow().is_empty());\n");
                            out.push_str("    }\n\n");
                        },
                        ActionTarget::Call(call) => {
                            out.push_str("    #[test]\n");
                            out.push_str(&format!("    fn test_call_{}_{}_on_{}_invokes_{}() {{\n", ctx.name, role.name, event_safe, call.function.replace(".", "_")));
                            out.push_str("        let effects = RecordingEffects::new();\n");
                            out.push_str(&format!("        let data = {}::default();\n", role_type));
                            out.push_str(&format!("        handle_{}_{}(&Contexto::{}, &data, &effects);\n", role.name, event_safe, ctx.name));
                            out.push_str(&format!("        assert!(effects.was_called(\"{}\"));\n", call.function));
                            out.push_str("    }\n\n");
                        }
                    }
                }
            }
        }
    }
}

fn generate_exhaustiveness_test(program: &Program, out: &mut String) {
    let mut contexts = Vec::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            contexts.push(ctx.name.clone());
        }
    }

    out.push_str("    // === Exhaustiveness Test ===\n\n");
    out.push_str("    #[test]\n");
    out.push_str("    fn test_exhaustive_contexto_enum() {\n");
    out.push_str("        let all_contexts = vec![\n");
    for ctx in &contexts {
        out.push_str(&format!("            Contexto::{},\n", ctx));
    }
    out.push_str("        ];\n");
    out.push_str(&format!("        assert_eq!(all_contexts.len(), {});\n", contexts.len()));
    out.push_str("    }\n\n");
}

fn generate_on_entry_tests(program: &Program, meta: &SystemMetadata, out: &mut String) {
    out.push_str("    // === On-Entry Effect Tests ===\n\n");
    
    // Build a map of target -> (source, event) to find how to reach a context
    let mut reachability = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                if !trans.target.starts_with("[") {
                    reachability.entry(trans.target.clone()).or_insert_with(Vec::new).push((ctx.name.clone(), trans.event.clone()));
                }
            }
        }
    }

    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for effect in &ctx.effects {
                if let EffectTrigger::Lifecycle(ref s) = effect.trigger {
                    if s == "on_entry" {
                        out.push_str("    #[test]\n");
                        out.push_str(&format!("    fn test_on_entry_{}_{}() {{\n", ctx.name, effect.call.function.replace(".", "_")));
                        out.push_str("        let effects = RecordingEffects::new();\n");
                        
                        if let Some(sources) = reachability.get(&ctx.name) {
                            let (src, event) = &sources[0];
                            out.push_str(&format!("        let mut sys = System::new(Contexto::{}, &effects);\n", src));
                            out.push_str(&format!("        sys.handle_event(\"{}\");\n", event));
                            out.push_str(&format!("        assert!(effects.was_called(\"{}\"));\n", effect.call.function));
                        } else if &ctx.name == &meta.initial {
                             out.push_str(&format!("        let _sys = System::new(Contexto::{}, &effects);\n", ctx.name));
                             out.push_str(&format!("        assert!(effects.was_called(\"{}\"));\n", effect.call.function));
                        } else {
                            out.push_str("        // Context unreachable or no direct transition found for test automatic generation\n");
                        }
                        out.push_str("    }\n\n");
                    }
                }
            }
        }
    }
}

fn generate_fills_tests(program: &Program, meta: &SystemMetadata, out: &mut String) {
    out.push_str("    // === Fills Tests ===\n\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for fills in &ctx.fills {
                for role in &fills.roles {
                    let role_type = &role.datatype;
                    for action in &role.actions {
                        let event_safe = action.event.replace(".", "_");
                        // Positive test
                        out.push_str("    #[test]\n");
                        out.push_str(&format!("    fn test_fills_{}_{}_{}_{}_{}() {{\n", ctx.name, fills.target_context, fills.target_slot, role.name, event_safe));
                        out.push_str("        let effects = RecordingEffects::new();\n");
                        out.push_str(&format!("        let mut sys = System::new(Contexto::{}, &effects);\n", meta.initial));
                        // Navigate to overlay
                        out.push_str(&format!("        sys.state = Contexto::{};\n", fills.target_context));
                        out.push_str(&format!("        let data = {}::default();\n", role_type));
                        out.push_str(&format!("        handle_{}_{}(&sys.state, &data, &effects);\n", role.name, event_safe));
                        
                        match &action.target {
                            ActionTarget::Call(call) => {
                                out.push_str(&format!("        assert!(effects.was_called(\"{}\"));\n", call.function));
                            },
                            _ => {}
                        }
                        out.push_str("    }\n\n");
                    }
                }
            }
        }
    }
}
pub fn generate_mermaid_topology(program: &Program) -> String {
    let mut output = String::new();
    output.push_str("stateDiagram-v2\n\n");
    
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                let target = trans.target.replace("[", "").replace("]", "");
                output.push_str(&format!("    {} --> {} : {}\n", ctx.name, target, trans.event));
            }
        }
    }
    
    for def in &program.definitions {
        if let Definition::System(sys) = def {
            output.push_str(&format!("    [*] --> {}\n", sys.initial));
        }
    }

    output
}

pub fn generate_mermaid_details(program: &Program) -> Vec<(String, String)> {
    let mut details = Vec::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            if !ctx.roles.is_empty() || !ctx.effects.is_empty() {
                let mut output = String::new();
                output.push_str("stateDiagram-v2\n\n");
                output.push_str(&format!("    state {} {{\n", ctx.name));
                for role in &ctx.roles {
                    for action in &role.actions {
                        let target_label = match &action.target {
                            ActionTarget::Call(c) => c.function.clone(),
                            ActionTarget::Ignored => "ignored".to_string(),
                            ActionTarget::Forbidden => "forbidden".to_string(),
                        };
                        let event_safe = action.event.replace(".", "_");
                        output.push_str(&format!("        {}_{}_{} --> {}\n", ctx.name, event_safe, role.name, target_label));
                    }
                }
                for effect in &ctx.effects {
                    let trigger = match &effect.trigger {
                        EffectTrigger::Lifecycle(s) => s.replace("[", "").replace("]", ""),
                        EffectTrigger::Event(s) => s.replace(".", "_"),
                    };
                    output.push_str(&format!("        {}_{} --> {}\n", ctx.name, trigger, effect.call.function));
                }
                output.push_str("    }\n");
                details.push((ctx.name.clone(), output));
            }
        }
    }
    details
}

pub fn generate_audit(program: &Program) -> String {
    let mut output = String::new();
    let mut system_name = "Sistema Trenza".to_string();
    let mut initial = "N/A".to_string();

    for def in &program.definitions {
        if let Definition::System(sys) = def {
            system_name = sys.name.clone();
            initial = sys.initial.clone();
        }
    }

    output.push_str(&format!("# Audit Report: {}\n\n", system_name));
    output.push_str("## 1. System Topology\n");
    output.push_str(&format!("- **Initial Context**: `{}`\n", initial));
    
    output.push_str("\n### Transitions Table\n");
    output.push_str("| From Context | Event | Target Context |\n");
    output.push_str("|--------------|-------|----------------|\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                output.push_str(&format!("| {} | {} | {} |\n", ctx.name, trans.event, trans.target));
            }
        }
    }

    output.push_str("\n## 2. Role Behavior Audit\n");
    output.push_str("| Context | Role | Event | Result |\n");
    output.push_str("|---------|------|-------|--------|\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    let result = match &action.target {
                        ActionTarget::Call(c) => format!("Call: `{}`", c.function),
                        ActionTarget::Ignored => "⚠️ Ignored".to_string(),
                        ActionTarget::Forbidden => "🚫 Forbidden".to_string(),
                    };
                    output.push_str(&format!("| {} | {} | {} | {} |\n", ctx.name, role.name, action.event, result));
                }
            }
        }
    }

    output.push_str("\n## 3. Formal Verification Summary\n");
    output.push_str("- [x] **Rule 1: Completeness** - verified by exhaustive match on Strand 1.\n");
    output.push_str("- [x] **Rule 2: Determinism** - verified by DSL grammar and validator.\n");
    output.push_str("- [x] **Rule 3: Reachability** - verified by topological analysis.\n");
    output.push_str("- [x] **Rule 4: Return** - verified by reverse topological search (no sink states).\n");
    output.push_str("- [x] **Rule 5: Role Exhaustiveness** - verified by cross-context role presence check.\n");
    output.push_str("- [x] **Rule 6: Data Conformance (GDPR)** - verified by role access validation.\n");
    
    output.push_str("\n---\n*Report generated by Trenza CLI v0.1.0* - Proof of Correctness by Design.\n");

    output
}
