// Auto-generated by Trenza DSL Compiler (Strand 1 - WASM Bridge)

export enum Contexto {
}

export interface Effects {
}

/**
 * Bridge entre el nucleo WASM de Trenza y el entorno de ejecucion TS.
 */
export class TrenzaSystem {
    private interpreter: any; // Type: InterpreterWasm
    private effects: Effects;

    constructor(interpreter: any, effects: Effects) {
        this.interpreter = interpreter;
        this.effects = effects;
    }

    public get current_state(): Contexto {
        return this.interpreter.get_state() as Contexto;
    }

    public get concurrent_states(): Set<Contexto> {
        return new Set(this.interpreter.get_concurrent_states() as Contexto[]);
    }

    /**
     * Despacha un evento al nucleo WASM y ejecuta los efectos resultantes.
     */
    public dispatch(event: string, payload: any = {}): void {
        const resultJson = this.interpreter.dispatch(event, JSON.stringify(payload));
        const result = JSON.parse(resultJson);

        if (result.triggered_effects) {
            for (const effect of result.triggered_effects) {
                const funcName = effect.name.replace(/\./g, '_');
                if (typeof (this.effects as any)[funcName] === 'function') {
                    (this.effects as any)[funcName](...effect.args);
                }
            }
        }
    }
}

