// Auto-generated by Trenza DSL Compiler (Strand 1 - WASM Bridge)

export enum Contexto {
    MenuConfiguracion = "MenuConfiguracion",
    ModalAcercaDe = "ModalAcercaDe",
    ModalComentario = "ModalComentario",
    ModalCrearActividad = "ModalCrearActividad",
    ModalCrearTarea = "ModalCrearTarea",
    ModalEditarActividad = "ModalEditarActividad",
    ModalEditarTarea = "ModalEditarTarea",
    ModalHistorial = "ModalHistorial",
    Historial7Dias = "Historial7Dias",
    Historial30Dias = "Historial30Dias",
    ModalReset = "ModalReset",
    ResetFase1 = "ResetFase1",
    ResetFase2 = "ResetFase2",
    ResetFase3 = "ResetFase3",
    ModalSeleccionActividad = "ModalSeleccionActividad",
    ModoEdicion = "ModoEdicion",
    ModoNormal = "ModoNormal",
    SesionActiva = "SesionActiva",
}

export interface TipoTarea {
    tipoId: string;
    nombre: string;
    icono: string;
    usos7d: number;
    actividades_permitidas: string[];
}

export interface Tarea {
    tareaId: string;
    tipoId: string;
    actividadId: string;
    nombre: string;
    icono: string;
}

export interface Actividad {
    id: string;
    nombre: string;
    color: string;
    permanente: boolean;
}

export interface Sesion {
    sesionId: string;
    tareaId: string;
    inicio: number;
    notas?: string;
}

export interface CampoTexto {
    id: string;
    valor: string;
    valido: boolean;
}

export interface CampoNumerico {
    id: string;
    valor: number;
    minimo: number;
}

export interface Boton {
    id: string;
    etiqueta: string;
    habilitado: boolean;
}

export interface Checkbox {
    id: string;
    etiqueta: string;
    marcado: boolean;
}

export interface SelectorColor {
    id: string;
    opciones: string[];
    seleccionado: string;
}

export interface SelectorIcono {
    id: string;
    iconos: string[];
    seleccionado: string;
    filtro: string;
}

export interface Pestana {
    id: string;
    etiqueta: string;
}

export interface ItemMenu {
    id: string;
    etiqueta: string;
}

export interface DiaHistorial {
    timestamp: number;
    total: number;
    por_actividad: ResumenActividad[];
}

export interface ResumenActividad {
    actividadId: string;
    actividadNombre: string;
    actividadColor: string;
    tiempo: number;
}

export interface OpcionActividad {
    id: string;
    nombre: string;
    color: string;
    permanente: boolean;
    conservar: boolean;
    marcado: boolean;
}

export interface Effects {
    abrirAcercaDe(): void;
    abrirCrearActividad(): void;
    abrirCrearTarea(): void;
    abrirEditarActividad(arg0: any): void;
    abrirEditarTarea(arg0: any): void;
    abrirHistorial(): void;
    abrirMenuConfiguracion(): void;
    abrirReset(): void;
    activarEdicion(): void;
    actualizarComentario(arg0: any): void;
    actualizarConfirmacion(arg0: any): void;
    actualizarGridVisible(): void;
    actualizarNombre(arg0: any): void;
    actualizarNombreActividad(arg0: any): void;
    actualizarNombreNuevaActividad(arg0: any): void;
    actualizarNuevoNombre(arg0: any): void;
    actualizarRetroactivo(arg0: any): void;
    actualizar_actividad(arg0: any, arg1: any, arg2: any, arg3: any): void;
    avanzarAFase2(): void;
    avanzarAFase3(): void;
    calcular_tiempo_transcurrido(arg0: any): void;
    cambiarA30Dias(): void;
    cambiarA7Dias(): void;
    cambiarPestana(arg0: any): void;
    cancelar(): void;
    cargar_historial(arg0: any): void;
    cargar_tiempo_acumulado(): void;
    cerrar(): void;
    confirmarInicio(): void;
    crear_actividad(arg0: any, arg1: any, arg2: any): void;
    crear_tipo_tarea(arg0: any, arg1: any, arg2: any): void;
    desactivarEdicion(): void;
    descargar_csv(): void;
    editar_tipo_tarea(arg0: any, arg1: any, arg2: any): void;
    ejecutarReset(): void;
    elegirActividad(arg0: any): void;
    exportarCSV(): void;
    filtrarIconos(arg0: any): void;
    filtrarIconosCrear(arg0: any): void;
    guardarEdicion(): void;
    guardarEdicionActividad(): void;
    guardarNuevaActividad(): void;
    guardarNuevaTarea(): void;
    iniciarTarea(arg0: any): void;
    iniciar_sesion(arg0: any, arg1: any, arg2: any, arg3: any): void;
    marcarPermanente(arg0: any): void;
    marcarPermanenteNueva(arg0: any): void;
    marcarSustituir(arg0: any): void;
    reset_datos(arg0: any): void;
    retrocederAFase1(): void;
    retrocederAFase2(): void;
    seleccionarColor(arg0: any): void;
    seleccionarColorNuevo(arg0: any): void;
    seleccionarIcono(arg0: any): void;
    seleccionarIconoNuevo(arg0: any): void;
    seleccionarTipoTarea(arg0: any): void;
    toggleActividadPermitida(arg0: any, arg1: any): void;
    toggleConservar(arg0: any, arg1: any): void;
    verificar_conexion(): void;
}

/**
 * Bridge entre el nucleo WASM de Trenza y el entorno de ejecucion TS.
 */
export class TrenzaSystem {
    private interpreter: any; // Type: InterpreterWasm
    private effects: Effects;

    constructor(interpreter: any, effects: Effects) {
        this.interpreter = interpreter;
        this.effects = effects;
    }

    public get current_state(): Contexto {
        return this.interpreter.get_state() as Contexto;
    }

    public get concurrent_states(): Set<Contexto> {
        return new Set([this.current_state]);
    }

    /**
     * Despacha un evento al nucleo WASM y ejecuta los efectos resultantes.
     */
    public dispatch(event: string, payload: any = {}): void {
        const resultJson = this.interpreter.dispatch(event, JSON.stringify(payload));
        const result = JSON.parse(resultJson);

        if (result.triggered_effects) {
            for (const effect of result.triggered_effects) {
                const funcName = effect.name.replace(/\./g, '_');
                if (typeof (this.effects as any)[funcName] === 'function') {
                    (this.effects as any)[funcName](...effect.args);
                }
            }
        }
    }
}

