// Auto-generated by Trenza DSL Compiler
// Compiler Profile: pro

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Contexto {
    EsperandoCredenciales,
    Autenticando,
    SesionActiva,
}

pub struct System {
    pub state: Contexto,
}

impl System {
    pub fn new(initial: Contexto) -> Self {
        Self { state: initial }
    }

    pub fn handle_event(&mut self, event: &str) {
        match self.state {
            Contexto::EsperandoCredenciales => {
                match event {
                    "iniciarAutenticacion" => self.state = Contexto::Autenticando,
                    _ => {},
                }
            },
            Contexto::Autenticando => {
                match event {
                    "verificar_credenciales.ok" => self.state = Contexto::SesionActiva,
                    "verificar_credenciales.error" => self.state = Contexto::EsperandoCredenciales,
                    _ => {},
                }
            },
            Contexto::SesionActiva => {
                match event {
                    "cerrar_sesion.ok" => self.state = Contexto::EsperandoCredenciales,
                    "cerrar_sesion.error" => self.state = Contexto::EsperandoCredenciales,
                    _ => {},
                }
            },
        }
    }
}

pub fn handle_boton_login_tap(ctx: &Contexto) {
    match ctx {
        Contexto::EsperandoCredenciales => {
            // execute iniciarAutenticacion
        },
        Contexto::Autenticando => {
            // ignored
        },
        Contexto::SesionActiva => {
            panic!("Forbidden action called in context SesionActiva");
        },
    }
}

pub fn handle_boton_logout_tap(ctx: &Contexto) {
    match ctx {
        Contexto::EsperandoCredenciales => {
            panic!("Forbidden action called in context EsperandoCredenciales");
        },
        Contexto::Autenticando => {
            panic!("Forbidden action called in context Autenticando");
        },
        Contexto::SesionActiva => {
            // execute cerrar_sesion
        },
    }
}

pub fn handle_formulario_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::EsperandoCredenciales => {
            // ignored
        },
        Contexto::Autenticando => {
            // ignored
        },
        Contexto::SesionActiva => {
            panic!("Forbidden action called in context SesionActiva");
        },
    }
}

pub fn handle_formulario_submit(ctx: &Contexto) {
    match ctx {
        Contexto::EsperandoCredenciales => {
            // execute iniciarAutenticacion
        },
        Contexto::Autenticando => {
            // ignored
        },
        Contexto::SesionActiva => {
            panic!("Forbidden action called in context SesionActiva");
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transition_EsperandoCredenciales_on_iniciarAutenticacion() {
        let mut sys = System::new(Contexto::EsperandoCredenciales);
        sys.handle_event("iniciarAutenticacion");
        assert_eq!(sys.state, Contexto::Autenticando);
    }

    #[test]
    fn test_transition_Autenticando_on_verificar_credenciales_ok() {
        let mut sys = System::new(Contexto::Autenticando);
        sys.handle_event("verificar_credenciales.ok");
        assert_eq!(sys.state, Contexto::SesionActiva);
    }

    #[test]
    fn test_transition_Autenticando_on_verificar_credenciales_error() {
        let mut sys = System::new(Contexto::Autenticando);
        sys.handle_event("verificar_credenciales.error");
        assert_eq!(sys.state, Contexto::EsperandoCredenciales);
    }

    #[test]
    fn test_transition_SesionActiva_on_cerrar_sesion_ok() {
        let mut sys = System::new(Contexto::SesionActiva);
        sys.handle_event("cerrar_sesion.ok");
        assert_eq!(sys.state, Contexto::EsperandoCredenciales);
    }

    #[test]
    fn test_transition_SesionActiva_on_cerrar_sesion_error() {
        let mut sys = System::new(Contexto::SesionActiva);
        sys.handle_event("cerrar_sesion.error");
        assert_eq!(sys.state, Contexto::EsperandoCredenciales);
    }

    #[test]
    #[should_panic]
    fn test_forbidden_EsperandoCredenciales_boton_logout_on_tap() {
        handle_boton_logout_tap(&Contexto::EsperandoCredenciales);
    }

    #[test]
    #[should_panic]
    fn test_forbidden_Autenticando_boton_logout_on_tap() {
        handle_boton_logout_tap(&Contexto::Autenticando);
    }

    #[test]
    #[should_panic]
    fn test_forbidden_SesionActiva_formulario_on_submit() {
        handle_formulario_submit(&Contexto::SesionActiva);
    }

    #[test]
    #[should_panic]
    fn test_forbidden_SesionActiva_formulario_on_cambio() {
        handle_formulario_cambio(&Contexto::SesionActiva);
    }

    #[test]
    #[should_panic]
    fn test_forbidden_SesionActiva_boton_login_on_tap() {
        handle_boton_login_tap(&Contexto::SesionActiva);
    }

}
