// Auto-generated by Trenza DSL Compiler
// Compiler Profile: pro

#[derive(Debug, Clone, PartialEq)]
pub enum Contexto {
    Procesando,
    PedidoCancelado,
}

// Handler for role pedido on cancelar
pub fn handle_pedido_cancelar(ctx: &Contexto) {
    match ctx {
        Contexto::Procesando => {
            println!("[audit] Legal: Registro de cancelación de pedido por usuario");
            // execute cancelarPedido
        },
        _ => unimplemented!("Action not allowed in this context"),
    }
}

