// Auto-generated by Trenza DSL Compiler
// Compiler Profile: pre
// Concurrency Mode: composite

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Contexto {
    Base,
    Popup,
    Auxiliar,
}

use std::collections::HashSet;

pub struct System {
    pub state: Contexto,
    pub concurrent_states: HashSet<Contexto>,
}

impl System {
    pub fn new(initial: Contexto) -> Self {
        let mut concurrent_states = HashSet::new();
        concurrent_states.insert(Contexto::Auxiliar);
        Self { state: initial, concurrent_states }
    }

    pub fn handle_event(&mut self, event: &str) {
        // Evaluate concurrent states sequentially (Composite Mode)
        if self.concurrent_states.contains(&Contexto::Auxiliar) {
            // In a full composite synthesis, we evaluate Auxiliar logic here
        }

        // Evaluate main state
        match self.state {
            Contexto::Base => {
                match event {
                    "abrir" => self.state = Contexto::Popup,
                    "activar" => self.state = Contexto::Auxiliar,
                    _ => {},
                }
            },
            Contexto::Popup => {
                match event {
                    "cerrar" => self.state = Contexto::Base,
                    _ => {},
                }
            },
            Contexto::Auxiliar => {
                match event {
                    "desactivar" => self.state = Contexto::Base,
                    _ => {},
                }
            },
        }
    }
}

pub fn handle_boton_tap(ctx: &Contexto) {
    match ctx {
        Contexto::Base => {
            println!("[telemetry] context=Base, role=boton, event=tap");
            // execute abrir
        },
        Contexto::Popup => {
            println!("[telemetry] context=Popup, role=boton, event=tap");
            // execute cerrar
        },
        Contexto::Auxiliar => {
            println!("[telemetry] context=Auxiliar, role=boton, event=tap");
            // ignored
        },
    }
}

pub fn handle_helper_tap(ctx: &Contexto) {
    match ctx {
        Contexto::Base => {
            println!("[telemetry] context=Base, role=helper, event=tap");
            // ignored
        },
        Contexto::Popup => {
            println!("[telemetry] context=Popup, role=helper, event=tap");
            // ignored
        },
        Contexto::Auxiliar => {
            println!("[telemetry] context=Auxiliar, role=helper, event=tap");
            // execute ayudar
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transition_Base_on_abrir() {
        let mut sys = System::new(Contexto::Base);
        sys.handle_event("abrir");
        assert_eq!(sys.state, Contexto::Popup);
    }

    #[test]
    fn test_transition_Base_on_activar() {
        let mut sys = System::new(Contexto::Base);
        sys.handle_event("activar");
        assert_eq!(sys.state, Contexto::Auxiliar);
    }

    #[test]
    fn test_transition_Popup_on_cerrar() {
        let mut sys = System::new(Contexto::Popup);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::Base);
    }

    #[test]
    fn test_transition_Auxiliar_on_desactivar() {
        let mut sys = System::new(Contexto::Auxiliar);
        sys.handle_event("desactivar");
        assert_eq!(sys.state, Contexto::Base);
    }

}
