use crate::ast::*;
use std::collections::BTreeMap;

pub fn generate_rust(program: &Program, profile: &str) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by Trenza DSL Compiler\n");
    output.push_str(&format!("// Compiler Profile: {}\n\n", profile));
    
    // Gather contexts
    let mut contexts = Vec::new();
    for def in &program.definitions {
        if let Definition::Context(c) = def {
            contexts.push(c.name.clone());
        }
    }
    
    output.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    output.push_str("pub enum Contexto {\n");
    for ctx in &contexts {
        output.push_str(&format!("    {},\n", ctx));
    }
    output.push_str("}\n\n");

    let is_pre = profile == "pre";

    // Group actions by (role_name, event_name)
    // BTreeMap is used to ensure deterministic output grouping and alphabetical stability
    let mut grouped_actions: BTreeMap<(String, String), Vec<(String, RoleAction)>> = BTreeMap::new();
    
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    let key = (role.name.clone(), action.event.clone());
                    grouped_actions.entry(key).or_default().push((ctx.name.clone(), action.clone()));
                }
            }
        }
    }

    for ((role_name, event_name), handlers) in grouped_actions {
        output.push_str(&format!("// Handler for role {} on {}\n", role_name, event_name));
        output.push_str(&format!("pub fn handle_{}_{}(ctx: &Contexto) {{\n", role_name, event_name));
        output.push_str(&format!("    match ctx {{\n"));
        
        for (ctx_name, action) in handlers {
            output.push_str(&format!("        Contexto::{} => {{\n", ctx_name));
            
            if is_pre {
                output.push_str(&format!("            println!(\"[telemetry] context={}, role={}, event={}, action={}\");\n", ctx_name, role_name, event_name, action.call.function));
            }
            if let Some(deco) = &action.decorator {
                if deco.name == "audit" {
                    output.push_str(&format!("            println!(\"[audit] {}\");\n", deco.args));
                }
            }
            output.push_str(&format!("            // execute {}\n", action.call.function));
            
            output.push_str("        },\n");
        }
        
        output.push_str("        _ => unimplemented!(\"Action not allowed in this context\"),\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");
    }

    output
}

pub fn generate_mermaid(program: &Program) -> String {
    let mut output = String::new();
    output.push_str("stateDiagram-v2\n");
    
    // Initial state
    for def in &program.definitions {
        if let Definition::System(sys) = def {
            output.push_str(&format!("    [*] --> {}\n", sys.initial));
        }
    }
    output.push_str("\n");

    // Global transitions
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                output.push_str(&format!("    {} --> {} : {}\n", ctx.name, trans.target, trans.event));
            }
        }
    }
    output.push_str("\n");

    // Context internal states (roles and actions)
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            if !ctx.roles.is_empty() {
                output.push_str(&format!("    state {} {{\n", ctx.name));
                for role in &ctx.roles {
                    for action in &role.actions {
                        output.push_str(&format!("        {}_{} --> {}\n", action.event, role.name, action.call.function));
                    }
                }
                output.push_str("    }\n\n");
            }
        }
    }

    output
}
