use crate::ast::*;
use std::collections::BTreeMap;

pub fn generate_rust(program: &Program, profile: &str) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by Trenza DSL Compiler\n");
    output.push_str(&format!("// Compiler Profile: {}\n\n", profile));
    
    // 1. Context Enum
    let mut contexts = Vec::new();
    for def in &program.definitions {
        if let Definition::Context(c) = def {
            contexts.push(c.name.clone());
        }
    }
    
    output.push_str("#[derive(Debug, Clone, Copy, PartialEq)]\n");
    output.push_str("pub enum Contexto {\n");
    for ctx in &contexts {
        output.push_str(&format!("    {},\n", ctx));
    }
    output.push_str("}\n\n");

    let is_pre = profile == "pre";

    // 2. System Structure and Transition Logic
    output.push_str("pub struct System {\n");
    output.push_str("    pub state: Contexto,\n");
    output.push_str("}\n\n");

    output.push_str("impl System {\n");
    output.push_str("    pub fn new(initial: Contexto) -> Self {\n");
    output.push_str("        Self { state: initial }\n");
    output.push_str("    }\n\n");

    output.push_str("    pub fn handle_event(&mut self, event: &str) {\n");
    output.push_str("        match self.state {\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            output.push_str(&format!("            Contexto::{} => {{\n", ctx.name));
            output.push_str("                match event {\n");
            for trans in &ctx.transitions {
                if trans.target == "[stay]" {
                    output.push_str(&format!("                    \"{}\" => {{}},\n", trans.event));
                } else {
                    output.push_str(&format!("                    \"{}\" => self.state = Contexto::{},\n", trans.event, trans.target));
                }
            }
            output.push_str("                    _ => {},\n");
            output.push_str("                }\n");
            output.push_str("            },\n");
        }
    }
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");

    // 3. Role/Event Handlers (Strand 1)
    let mut grouped_actions: BTreeMap<(String, String), Vec<(String, RoleAction)>> = BTreeMap::new();
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    let key = (role.name.clone(), action.event.clone());
                    grouped_actions.entry(key).or_default().push((ctx.name.clone(), action.clone()));
                }
            }
        }
    }

    for ((role_name, event_name), handlers) in grouped_actions {
        output.push_str(&format!("pub fn handle_{}_{}(ctx: &Contexto) {{\n", role_name, event_name.replace(".", "_")));
        output.push_str("    match ctx {\n");
        for (ctx_name, action) in handlers {
            output.push_str(&format!("        Contexto::{} => {{\n", ctx_name));
            if is_pre {
                output.push_str(&format!("            println!(\"[telemetry] context={}, role={}, event={}\");\n", ctx_name, role_name, event_name));
            }
            match &action.target {
                ActionTarget::Call(call) => {
                    output.push_str(&format!("            // execute {}\n", call.function));
                },
                ActionTarget::Ignored => {
                    output.push_str("            // ignored\n");
                },
                ActionTarget::Forbidden => {
                    output.push_str(&format!("            panic!(\"Forbidden action called in context {}\");\n", ctx_name));
                }
            }
            output.push_str("        },\n");
        }
        output.push_str("    }\n");
        output.push_str("}\n\n");
    }

    // 4. Algebraic Tests (Strand 2)
    output.push_str("#[cfg(test)]\nmod tests {\n    use super::*;\n\n");
    
    // Test transitions
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                output.push_str(&format!("    #[test]\n"));
                output.push_str(&format!("    fn test_transition_{}_on_{}() {{\n", ctx.name, trans.event.replace(".", "_")));
                output.push_str(&format!("        let mut sys = System::new(Contexto::{});\n", ctx.name));
                output.push_str(&format!("        sys.handle_event(\"{}\");\n", trans.event));
                output.push_str(&format!("        assert_eq!(sys.state, Contexto::{});\n", trans.target));
                output.push_str("    }\n\n");
            }
        }
    }

    // Test forbidden actions
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    if let ActionTarget::Forbidden = &action.target {
                        output.push_str("    #[test]\n");
                        output.push_str("    #[should_panic]\n");
                        output.push_str(&format!("    fn test_forbidden_{}_{}_on_{}() {{\n", ctx.name, role.name, action.event.replace(".", "_")));
                        output.push_str(&format!("        handle_{}_{}(&Contexto::{});\n", role.name, action.event.replace(".", "_"), ctx.name));
                        output.push_str("    }\n\n");
                    }
                }
            }
        }
    }

    output.push_str("}\n");

    output
}


pub fn generate_mermaid(program: &Program) -> String {
    let mut output = String::new();
    output.push_str("stateDiagram-v2\n");
    
    // Initial state
    for def in &program.definitions {
        if let Definition::System(sys) = def {
            output.push_str(&format!("    [*] --> {}\n", sys.initial));
        }
    }
    output.push_str("\n");

    // Global transitions
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                output.push_str(&format!("    {} --> {} : {}\n", ctx.name, trans.target, trans.event));
            }
        }
    }
    output.push_str("\n");

    // Context internal states (roles and actions)
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            if !ctx.roles.is_empty() || !ctx.effects.is_empty() {
                output.push_str(&format!("    state {} {{\n", ctx.name));
                for role in &ctx.roles {
                    for action in &role.actions {
                        let target_label = match &action.target {
                            ActionTarget::Call(c) => c.function.clone(),
                            ActionTarget::Ignored => "ignored".to_string(),
                            ActionTarget::Forbidden => "forbidden".to_string(),
                        };
                        output.push_str(&format!("        {}_{} --> {}\n", action.event.replace(".", "_"), role.name, target_label));
                    }
                }
                for effect in &ctx.effects {
                    let trigger = match &effect.trigger {
                        EffectTrigger::Lifecycle(s) => s.clone(),
                        EffectTrigger::Event(s) => s.clone(),
                    };
                    output.push_str(&format!("        [{}] --> {}\n", trigger, effect.call.function));
                }
                output.push_str("    }\n\n");
            }
        }
    }

    output
}

pub fn generate_audit(program: &Program) -> String {
    let mut output = String::new();
    let mut system_name = "Sistema Trenza".to_string();
    let mut initial = "N/A".to_string();

    for def in &program.definitions {
        if let Definition::System(sys) = def {
            system_name = sys.name.clone();
            initial = sys.initial.clone();
        }
    }

    output.push_str(&format!("# Audit Report: {}\n\n", system_name));
    output.push_str("## 1. System Topology\n");
    output.push_str(&format!("- **Initial Context**: `{}`\n", initial));
    
    output.push_str("\n### Transitions Table\n");
    output.push_str("| From Context | Event | Target Context |\n");
    output.push_str("|--------------|-------|----------------|\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for trans in &ctx.transitions {
                output.push_str(&format!("| {} | {} | {} |\n", ctx.name, trans.event, trans.target));
            }
        }
    }

    output.push_str("\n## 2. Role Behavior Audit\n");
    output.push_str("| Context | Role | Event | Result |\n");
    output.push_str("|---------|------|-------|--------|\n");
    for def in &program.definitions {
        if let Definition::Context(ctx) = def {
            for role in &ctx.roles {
                for action in &role.actions {
                    let result = match &action.target {
                        ActionTarget::Call(c) => format!("Call: `{}`", c.function),
                        ActionTarget::Ignored => "⚠️ Ignored".to_string(),
                        ActionTarget::Forbidden => "🚫 Forbidden".to_string(),
                    };
                    output.push_str(&format!("| {} | {} | {} | {} |\n", ctx.name, role.name, action.event, result));
                }
            }
        }
    }

    output.push_str("\n## 3. Formal Verification Summary\n");
    output.push_str("- [x] **Rule 1: Completeness** - verified by exhaustive match on Strand 1.\n");
    output.push_str("- [x] **Rule 2: Determinism** - verified by DSL grammar and validator.\n");
    output.push_str("- [x] **Rule 3: Reachability** - verified by topological analysis.\n");
    output.push_str("- [x] **Rule 6: Data Conformance (GDPR)** - verified by role access validation.\n");
    
    output.push_str("\n---\n*Report generated by Trenza CLI v0.1.0* - Proof of Correctness by Design.\n");

    output
}
