pub mod ast;
pub mod parser;
pub mod generator;
pub mod validator;

extern crate pest;
#[macro_use]
extern crate pest_derive;

use pest::Parser;
use std::fs;
use std::env;

use std::path::{Path, PathBuf};

fn get_all_trz_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                files.extend(get_all_trz_files(&path));
            } else if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("trz") {
                files.push(path);
            }
        }
    }
    files
}

#[derive(Parser)]
#[grammar = "trenza.pest"]
pub struct TrenzaParser;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("Uso: trenza-cli [generate] [--profile=pro|pre] [--concurrency=composite|threads] <archivo_o_directorio>");
        std::process::exit(1);
    }
    
    let mut is_generate = false;
    let mut profile = "pre".to_string();
    let mut concurrency = "composite".to_string();
    let mut filepath = "".to_string();

    for arg in &args[1..] {
        if arg == "generate" {
            is_generate = true;
        } else if arg.starts_with("--profile=") {
            profile = arg.split('=').nth(1).unwrap().to_string();
        } else if arg.starts_with("--concurrency=") {
            concurrency = arg.split('=').nth(1).unwrap().to_string();
        } else {
            filepath = arg.to_string();
        }
    }

    if filepath.is_empty() {
        eprintln!("Debe especificar una ruta .trz o un directorio");
        std::process::exit(1);
    }

    let path = Path::new(&filepath);
    let mut all_definitions = Vec::new();

    let mut files_to_parse = if path.is_dir() {
        get_all_trz_files(path)
    } else {
        vec![path.to_path_buf()]
    };

    if files_to_parse.is_empty() {
        eprintln!("No se encontraron archivos .trz en la ruta especificada.");
        std::process::exit(1);
    }

    files_to_parse.sort_by_key(|p| {
        let name = p.file_name().unwrap_or_default().to_string_lossy().to_string();
        if name == "system.trz" { 0 } else { 1 }
    });

    for file in &files_to_parse {
        let mut unparsed_file = fs::read_to_string(file).expect("No se pudo leer un archivo");
        unparsed_file = unparsed_file.trim_start_matches('\u{feff}').to_string();
        match parser::parse_file(&unparsed_file) {
            Ok(ast) => {
                println!("✅ Archivo '{}' leido y parseado.", file.display());
                all_definitions.extend(ast.definitions);
            },
            Err(e) => {
                eprintln!("❌ Error de sintaxis en '{}':\n{}", file.display(), e);
                std::process::exit(1);
            }
        }
    }

    let program_ast = ast::Program { definitions: all_definitions };

    match validator::verify(&program_ast) {
        Ok(_) => {
            println!("- ✅ Verificación Semántica: Superada impecablemente para {} archivos.", files_to_parse.len());
            if is_generate {
                let rust_code = generator::generate_rust(&program_ast, &profile, &concurrency);
                let mermaid_code = generator::generate_mermaid(&program_ast);
                let audit_doc = generator::generate_audit(&program_ast);

                let mut system_name = "project".to_string();
                for def in &program_ast.definitions {
                    if let ast::Definition::System(sys) = def {
                        system_name = sys.name.clone();
                        break;
                    }
                }

                let out_rust = format!("{}_out.rs", system_name);
                let out_mermaid = format!("{}_out.mermaid", system_name);
                let out_audit = format!("{}_out_audit.md", system_name);
                let out_viz = format!("{}_viz.md", system_name);
                let out_html = format!("{}_summary.html", system_name);

                let viz_md = format!(
                    "# System Visualization: {}\n\n```mermaid\n{}\n```\n\n*Generated by Trenza CLI*",
                    system_name, mermaid_code
                );

                let html_report = format!(
                    "<!DOCTYPE html><html><head><title>Trenza: {}</title><script src='https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'></script><style>body {{ font-family: sans-serif; background: #f0f2f5; margin: 0; padding: 20px; }} .container {{ max-width: 1200px; margin: auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }} .mermaid {{ background: #fafafa; border: 1px solid #eee; border_radius: 8px; padding: 20px; margin: 20px 0; }} h1 {{ color: #1a73e8; }} h2 {{ border-bottom: 2px solid #1a73e8; padding-bottom: 10px; margin-top: 40px; }} .audit {{ font-family: monospace; background: #202124; color: #e8eaed; padding: 20px; border-radius: 8px; overflow-x: auto; line-height: 1.6; }}</style></head><body><div class='container'><h1>Trenza System Overview: {}</h1><p>Formal Verification Passport for project <strong>{}</strong></p><div class='mermaid'>{}</div><h2>Audit Report (Strand 4)</h2><div class='audit'>{}</div></div><script>mermaid.initialize({{startOnLoad:true, theme: 'forest'}});</script></body></html>",
                    system_name, system_name, system_name, mermaid_code, audit_doc.replace("\n", "<br>")
                );

                fs::write(&out_rust, rust_code).expect("No se pudo escribir el archivo Rust");
                fs::write(&out_mermaid, mermaid_code).expect("No se pudo escribir el archivo Mermaid");
                fs::write(&out_audit, audit_doc).expect("No se pudo escribir el archivo Audit");
                fs::write(&out_viz, viz_md).expect("No se pudo escribir el archivo Viz");
                fs::write(&out_html, html_report).expect("No se pudo escribir el archivo HTML");

                println!("- ✅ Código Strand 1 (Rust) generado en: {}", out_rust);
                println!("- ✅ Código Strand 3 (Mermaid) generado en: {}", out_mermaid);
                println!("- ✅ Informe Strand 4 (Auditoría) generado en: {}", out_audit);
                println!("- ✅ Vista de Hebras (Markdown) generado en: {}", out_viz);
                println!("- ✅ Reporte Interactivo (HTML) generado en: {}", out_html);
            } else {
                println!("- IEFBR14 completado: El programa es válido y la hebra es limpia.");
            }
        },
        Err(errores) => {
            eprintln!("❌ Verificación Semántica Fallida:");
            for err in errores {
                eprintln!("  {}", err);
            }
            std::process::exit(1);
        }
    }
}
