// Auto-generated by Trenza DSL Compiler
// Compiler Profile: pre
// Concurrency Mode: composite

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum Contexto {
    MenuConfiguracion,
    ModalAcercaDe,
    ModalComentario,
    ModalCrearActividad,
    ModalCrearTarea,
    ModalEditarActividad,
    ModalEditarTarea,
    ModalHistorial,
    Historial7Dias,
    Historial30Dias,
    ModalReset,
    ResetFase1,
    ResetFase2,
    ResetFase3,
    ModalSeleccionActividad,
    ModoEdicion,
    ModoNormal,
    SesionActiva,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TipoTarea {
    pub tipoId: String,
    pub nombre: String,
    pub icono: String,
    pub usos7d: i32,
    pub actividades_permitidas: Vec<String>,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tarea {
    pub tareaId: String,
    pub tipoId: String,
    pub actividadId: String,
    pub nombre: String,
    pub icono: String,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Actividad {
    pub id: String,
    pub nombre: String,
    pub color: String,
    pub permanente: bool,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Sesion {
    pub sesionId: String,
    pub tareaId: String,
    pub inicio: u64,
    pub notas: Option<String>,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CampoTexto {
    pub id: String,
    pub valor: String,
    pub valido: bool,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CampoNumerico {
    pub id: String,
    pub valor: i32,
    pub minimo: i32,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Boton {
    pub id: String,
    pub etiqueta: String,
    pub habilitado: bool,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Checkbox {
    pub id: String,
    pub etiqueta: String,
    pub marcado: bool,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SelectorColor {
    pub id: String,
    pub opciones: Vec<String>,
    pub seleccionado: String,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SelectorIcono {
    pub id: String,
    pub iconos: Vec<String>,
    pub seleccionado: String,
    pub filtro: String,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Pestana {
    pub id: String,
    pub etiqueta: String,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemMenu {
    pub id: String,
    pub etiqueta: String,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DiaHistorial {
    pub timestamp: u64,
    pub total: i32,
    pub por_actividad: Vec<ResumenActividad>,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResumenActividad {
    pub actividadId: String,
    pub actividadNombre: String,
    pub actividadColor: String,
    pub tiempo: i32,
}

#[allow(non_snake_case)]
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpcionActividad {
    pub id: String,
    pub nombre: String,
    pub color: String,
    pub permanente: bool,
    pub conservar: bool,
    pub marcado: bool,
}

pub trait Effects {
    fn abrirAcercaDe(&self, );
    fn abrirCrearActividad(&self, );
    fn abrirCrearTarea(&self, );
    fn abrirEditarActividad(&self, arg0: &String);
    fn abrirEditarTarea(&self, arg0: &String);
    fn abrirHistorial(&self, );
    fn abrirMenuConfiguracion(&self, );
    fn abrirReset(&self, );
    fn activarEdicion(&self, );
    fn actualizarComentario(&self, arg0: &String);
    fn actualizarConfirmacion(&self, arg0: &String);
    fn actualizarGridVisible(&self, );
    fn actualizarNombre(&self, arg0: &String);
    fn actualizarNombreActividad(&self, arg0: &String);
    fn actualizarNombreNuevaActividad(&self, arg0: &String);
    fn actualizarNuevoNombre(&self, arg0: &String);
    fn actualizarRetroactivo(&self, arg0: &i32);
    fn actualizar_actividad(&self, arg0: &str, arg1: &str, arg2: &str, arg3: &str);
    fn avanzarAFase2(&self, );
    fn avanzarAFase3(&self, );
    fn calcular_tiempo_transcurrido(&self, arg0: &str);
    fn cambiarA30Dias(&self, );
    fn cambiarA7Dias(&self, );
    fn cambiarPestana(&self, arg0: &str);
    fn cancelar(&self, );
    fn cargar_historial(&self, arg0: &str);
    fn cargar_tiempo_acumulado(&self, );
    fn cerrar(&self, );
    fn confirmarInicio(&self, );
    fn crear_actividad(&self, arg0: &str, arg1: &str, arg2: &str);
    fn crear_tipo_tarea(&self, arg0: &str, arg1: &str, arg2: &str);
    fn desactivarEdicion(&self, );
    fn descargar_csv(&self, );
    fn editar_tipo_tarea(&self, arg0: &str, arg1: &str, arg2: &str);
    fn ejecutarReset(&self, );
    fn elegirActividad(&self, arg0: &String);
    fn exportarCSV(&self, );
    fn filtrarIconos(&self, arg0: &String);
    fn filtrarIconosCrear(&self, arg0: &String);
    fn guardarEdicion(&self, );
    fn guardarEdicionActividad(&self, );
    fn guardarNuevaActividad(&self, );
    fn guardarNuevaTarea(&self, );
    fn iniciarTarea(&self, arg0: &String);
    fn iniciar_sesion(&self, arg0: &str, arg1: &str, arg2: &str, arg3: &str);
    fn marcarPermanente(&self, arg0: &bool);
    fn marcarPermanenteNueva(&self, arg0: &bool);
    fn marcarSustituir(&self, arg0: &bool);
    fn parar_sesion(&self, );
    fn reset_datos(&self, arg0: &str);
    fn retrocederAFase1(&self, );
    fn retrocederAFase2(&self, );
    fn seleccionarColor(&self, arg0: &String);
    fn seleccionarColorNuevo(&self, arg0: &String);
    fn seleccionarIcono(&self, arg0: &String);
    fn seleccionarIconoNuevo(&self, arg0: &String);
    fn seleccionarTipoTarea(&self, arg0: &String);
    fn toggleActividadPermitida(&self, arg0: &String, arg1: &bool);
    fn toggleConservar(&self, arg0: &String, arg1: &bool);
    fn verificar_conexion(&self, );
}

pub struct NoOpEffects;
impl Effects for NoOpEffects {
    fn abrirAcercaDe(&self, ) {}
    fn abrirCrearActividad(&self, ) {}
    fn abrirCrearTarea(&self, ) {}
    fn abrirEditarActividad(&self, _arg0: &String) {}
    fn abrirEditarTarea(&self, _arg0: &String) {}
    fn abrirHistorial(&self, ) {}
    fn abrirMenuConfiguracion(&self, ) {}
    fn abrirReset(&self, ) {}
    fn activarEdicion(&self, ) {}
    fn actualizarComentario(&self, _arg0: &String) {}
    fn actualizarConfirmacion(&self, _arg0: &String) {}
    fn actualizarGridVisible(&self, ) {}
    fn actualizarNombre(&self, _arg0: &String) {}
    fn actualizarNombreActividad(&self, _arg0: &String) {}
    fn actualizarNombreNuevaActividad(&self, _arg0: &String) {}
    fn actualizarNuevoNombre(&self, _arg0: &String) {}
    fn actualizarRetroactivo(&self, _arg0: &i32) {}
    fn actualizar_actividad(&self, _arg0: &str, _arg1: &str, _arg2: &str, _arg3: &str) {}
    fn avanzarAFase2(&self, ) {}
    fn avanzarAFase3(&self, ) {}
    fn calcular_tiempo_transcurrido(&self, _arg0: &str) {}
    fn cambiarA30Dias(&self, ) {}
    fn cambiarA7Dias(&self, ) {}
    fn cambiarPestana(&self, _arg0: &str) {}
    fn cancelar(&self, ) {}
    fn cargar_historial(&self, _arg0: &str) {}
    fn cargar_tiempo_acumulado(&self, ) {}
    fn cerrar(&self, ) {}
    fn confirmarInicio(&self, ) {}
    fn crear_actividad(&self, _arg0: &str, _arg1: &str, _arg2: &str) {}
    fn crear_tipo_tarea(&self, _arg0: &str, _arg1: &str, _arg2: &str) {}
    fn desactivarEdicion(&self, ) {}
    fn descargar_csv(&self, ) {}
    fn editar_tipo_tarea(&self, _arg0: &str, _arg1: &str, _arg2: &str) {}
    fn ejecutarReset(&self, ) {}
    fn elegirActividad(&self, _arg0: &String) {}
    fn exportarCSV(&self, ) {}
    fn filtrarIconos(&self, _arg0: &String) {}
    fn filtrarIconosCrear(&self, _arg0: &String) {}
    fn guardarEdicion(&self, ) {}
    fn guardarEdicionActividad(&self, ) {}
    fn guardarNuevaActividad(&self, ) {}
    fn guardarNuevaTarea(&self, ) {}
    fn iniciarTarea(&self, _arg0: &String) {}
    fn iniciar_sesion(&self, _arg0: &str, _arg1: &str, _arg2: &str, _arg3: &str) {}
    fn marcarPermanente(&self, _arg0: &bool) {}
    fn marcarPermanenteNueva(&self, _arg0: &bool) {}
    fn marcarSustituir(&self, _arg0: &bool) {}
    fn parar_sesion(&self, ) {}
    fn reset_datos(&self, _arg0: &str) {}
    fn retrocederAFase1(&self, ) {}
    fn retrocederAFase2(&self, ) {}
    fn seleccionarColor(&self, _arg0: &String) {}
    fn seleccionarColorNuevo(&self, _arg0: &String) {}
    fn seleccionarIcono(&self, _arg0: &String) {}
    fn seleccionarIconoNuevo(&self, _arg0: &String) {}
    fn seleccionarTipoTarea(&self, _arg0: &String) {}
    fn toggleActividadPermitida(&self, _arg0: &String, _arg1: &bool) {}
    fn toggleConservar(&self, _arg0: &String, _arg1: &bool) {}
    fn verificar_conexion(&self, ) {}
}

pub struct RecordingEffects {
    pub calls: std::cell::RefCell<Vec<String>>,
}
impl RecordingEffects {
    pub fn new() -> Self {
        Self { calls: std::cell::RefCell::new(Vec::new()) }
    }
    pub fn was_called(&self, func: &str) -> bool {
        self.calls.borrow().iter().any(|c| c.starts_with(func))
    }
}
impl Effects for RecordingEffects {
    fn abrirAcercaDe(&self, ) {
        self.calls.borrow_mut().push("abrirAcercaDe".to_string());
    }
    fn abrirCrearActividad(&self, ) {
        self.calls.borrow_mut().push("abrirCrearActividad".to_string());
    }
    fn abrirCrearTarea(&self, ) {
        self.calls.borrow_mut().push("abrirCrearTarea".to_string());
    }
    fn abrirEditarActividad(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("abrirEditarActividad({:?})", arg0));
    }
    fn abrirEditarTarea(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("abrirEditarTarea({:?})", arg0));
    }
    fn abrirHistorial(&self, ) {
        self.calls.borrow_mut().push("abrirHistorial".to_string());
    }
    fn abrirMenuConfiguracion(&self, ) {
        self.calls.borrow_mut().push("abrirMenuConfiguracion".to_string());
    }
    fn abrirReset(&self, ) {
        self.calls.borrow_mut().push("abrirReset".to_string());
    }
    fn activarEdicion(&self, ) {
        self.calls.borrow_mut().push("activarEdicion".to_string());
    }
    fn actualizarComentario(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("actualizarComentario({:?})", arg0));
    }
    fn actualizarConfirmacion(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("actualizarConfirmacion({:?})", arg0));
    }
    fn actualizarGridVisible(&self, ) {
        self.calls.borrow_mut().push("actualizarGridVisible".to_string());
    }
    fn actualizarNombre(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("actualizarNombre({:?})", arg0));
    }
    fn actualizarNombreActividad(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("actualizarNombreActividad({:?})", arg0));
    }
    fn actualizarNombreNuevaActividad(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("actualizarNombreNuevaActividad({:?})", arg0));
    }
    fn actualizarNuevoNombre(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("actualizarNuevoNombre({:?})", arg0));
    }
    fn actualizarRetroactivo(&self, arg0: &i32) {
        self.calls.borrow_mut().push(format!("actualizarRetroactivo({:?})", arg0));
    }
    fn actualizar_actividad(&self, arg0: &str, arg1: &str, arg2: &str, arg3: &str) {
        self.calls.borrow_mut().push(format!("actualizar_actividad({:?}, {:?}, {:?}, {:?})", arg0, arg1, arg2, arg3));
    }
    fn avanzarAFase2(&self, ) {
        self.calls.borrow_mut().push("avanzarAFase2".to_string());
    }
    fn avanzarAFase3(&self, ) {
        self.calls.borrow_mut().push("avanzarAFase3".to_string());
    }
    fn calcular_tiempo_transcurrido(&self, arg0: &str) {
        self.calls.borrow_mut().push(format!("calcular_tiempo_transcurrido({:?})", arg0));
    }
    fn cambiarA30Dias(&self, ) {
        self.calls.borrow_mut().push("cambiarA30Dias".to_string());
    }
    fn cambiarA7Dias(&self, ) {
        self.calls.borrow_mut().push("cambiarA7Dias".to_string());
    }
    fn cambiarPestana(&self, arg0: &str) {
        self.calls.borrow_mut().push(format!("cambiarPestana({:?})", arg0));
    }
    fn cancelar(&self, ) {
        self.calls.borrow_mut().push("cancelar".to_string());
    }
    fn cargar_historial(&self, arg0: &str) {
        self.calls.borrow_mut().push(format!("cargar_historial({:?})", arg0));
    }
    fn cargar_tiempo_acumulado(&self, ) {
        self.calls.borrow_mut().push("cargar_tiempo_acumulado".to_string());
    }
    fn cerrar(&self, ) {
        self.calls.borrow_mut().push("cerrar".to_string());
    }
    fn confirmarInicio(&self, ) {
        self.calls.borrow_mut().push("confirmarInicio".to_string());
    }
    fn crear_actividad(&self, arg0: &str, arg1: &str, arg2: &str) {
        self.calls.borrow_mut().push(format!("crear_actividad({:?}, {:?}, {:?})", arg0, arg1, arg2));
    }
    fn crear_tipo_tarea(&self, arg0: &str, arg1: &str, arg2: &str) {
        self.calls.borrow_mut().push(format!("crear_tipo_tarea({:?}, {:?}, {:?})", arg0, arg1, arg2));
    }
    fn desactivarEdicion(&self, ) {
        self.calls.borrow_mut().push("desactivarEdicion".to_string());
    }
    fn descargar_csv(&self, ) {
        self.calls.borrow_mut().push("descargar_csv".to_string());
    }
    fn editar_tipo_tarea(&self, arg0: &str, arg1: &str, arg2: &str) {
        self.calls.borrow_mut().push(format!("editar_tipo_tarea({:?}, {:?}, {:?})", arg0, arg1, arg2));
    }
    fn ejecutarReset(&self, ) {
        self.calls.borrow_mut().push("ejecutarReset".to_string());
    }
    fn elegirActividad(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("elegirActividad({:?})", arg0));
    }
    fn exportarCSV(&self, ) {
        self.calls.borrow_mut().push("exportarCSV".to_string());
    }
    fn filtrarIconos(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("filtrarIconos({:?})", arg0));
    }
    fn filtrarIconosCrear(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("filtrarIconosCrear({:?})", arg0));
    }
    fn guardarEdicion(&self, ) {
        self.calls.borrow_mut().push("guardarEdicion".to_string());
    }
    fn guardarEdicionActividad(&self, ) {
        self.calls.borrow_mut().push("guardarEdicionActividad".to_string());
    }
    fn guardarNuevaActividad(&self, ) {
        self.calls.borrow_mut().push("guardarNuevaActividad".to_string());
    }
    fn guardarNuevaTarea(&self, ) {
        self.calls.borrow_mut().push("guardarNuevaTarea".to_string());
    }
    fn iniciarTarea(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("iniciarTarea({:?})", arg0));
    }
    fn iniciar_sesion(&self, arg0: &str, arg1: &str, arg2: &str, arg3: &str) {
        self.calls.borrow_mut().push(format!("iniciar_sesion({:?}, {:?}, {:?}, {:?})", arg0, arg1, arg2, arg3));
    }
    fn marcarPermanente(&self, arg0: &bool) {
        self.calls.borrow_mut().push(format!("marcarPermanente({:?})", arg0));
    }
    fn marcarPermanenteNueva(&self, arg0: &bool) {
        self.calls.borrow_mut().push(format!("marcarPermanenteNueva({:?})", arg0));
    }
    fn marcarSustituir(&self, arg0: &bool) {
        self.calls.borrow_mut().push(format!("marcarSustituir({:?})", arg0));
    }
    fn parar_sesion(&self, ) {
        self.calls.borrow_mut().push("parar_sesion".to_string());
    }
    fn reset_datos(&self, arg0: &str) {
        self.calls.borrow_mut().push(format!("reset_datos({:?})", arg0));
    }
    fn retrocederAFase1(&self, ) {
        self.calls.borrow_mut().push("retrocederAFase1".to_string());
    }
    fn retrocederAFase2(&self, ) {
        self.calls.borrow_mut().push("retrocederAFase2".to_string());
    }
    fn seleccionarColor(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("seleccionarColor({:?})", arg0));
    }
    fn seleccionarColorNuevo(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("seleccionarColorNuevo({:?})", arg0));
    }
    fn seleccionarIcono(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("seleccionarIcono({:?})", arg0));
    }
    fn seleccionarIconoNuevo(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("seleccionarIconoNuevo({:?})", arg0));
    }
    fn seleccionarTipoTarea(&self, arg0: &String) {
        self.calls.borrow_mut().push(format!("seleccionarTipoTarea({:?})", arg0));
    }
    fn toggleActividadPermitida(&self, arg0: &String, arg1: &bool) {
        self.calls.borrow_mut().push(format!("toggleActividadPermitida({:?}, {:?})", arg0, arg1));
    }
    fn toggleConservar(&self, arg0: &String, arg1: &bool) {
        self.calls.borrow_mut().push(format!("toggleConservar({:?}, {:?})", arg0, arg1));
    }
    fn verificar_conexion(&self, ) {
        self.calls.borrow_mut().push("verificar_conexion".to_string());
    }
}

use std::collections::HashSet as StdHashSet;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Snapshot {
    pub base: Contexto,
    pub overlay_stack: Vec<Contexto>,
    pub concurrent: Vec<Contexto>,
    pub current: Contexto,
}

pub struct System<'a> {
    pub base: Contexto,
    pub overlay_stack: Vec<Contexto>,
    pub concurrent: StdHashSet<Contexto>,
    pub effects: &'a dyn Effects,
}

fn payload_str<'a>(p: &'a serde_json::Value, key: &str) -> &'a str {
    p.get(key).and_then(|v| v.as_str()).unwrap_or("")
}

impl<'a> System<'a> {
    pub fn new(initial: Contexto, effects: &'a dyn Effects) -> Self {
        Self {
            base: initial,
            overlay_stack: Vec::new(),
            concurrent: StdHashSet::new(),
            effects,
        }
    }

    pub fn current_state(&self) -> Contexto {
        self.overlay_stack.last().copied().unwrap_or(self.base)
    }

    pub fn snapshot(&self) -> Snapshot {
        Snapshot {
            base: self.base,
            overlay_stack: self.overlay_stack.clone(),
            concurrent: self.concurrent.iter().copied().collect(),
            current: self.current_state(),
        }
    }

    fn parent_overlay_of(c: Contexto) -> Option<Contexto> {
        match c {
            Contexto::Historial30Dias => Some(Contexto::ModalHistorial),
            Contexto::Historial7Dias => Some(Contexto::ModalHistorial),
            Contexto::ResetFase1 => Some(Contexto::ModalReset),
            Contexto::ResetFase2 => Some(Contexto::ModalReset),
            Contexto::ResetFase3 => Some(Contexto::ModalReset),
            _ => None,
        }
    }

    fn replace_top_or_push(&mut self, sub: Contexto) {
        let parent = Self::parent_overlay_of(sub);
        let same_parent = match (self.overlay_stack.last(), parent) {
            (Some(top), Some(_)) => Some(*top) == parent || Self::parent_overlay_of(*top) == parent,
            _ => false,
        };
        if same_parent {
            *self.overlay_stack.last_mut().unwrap() = sub;
        } else {
            self.overlay_stack.push(sub);
        }
    }

    pub fn handle_event(&mut self, event: &str) {
        self.dispatch(event, &serde_json::Value::Null);
    }

    pub fn dispatch(&mut self, event: &str, payload: &serde_json::Value) {
        let prev = self.current_state();
        self.dispatch_concurrent(event, payload);
        self.dispatch_main(event, payload);
        let new_current = self.current_state();
        if new_current != prev {
            self.run_on_entry(new_current, payload);
        }
    }

    fn dispatch_concurrent(&mut self, event: &str, payload: &serde_json::Value) {
        let _ = (event, payload);
        if self.concurrent.contains(&Contexto::SesionActiva) {
            match event {
                "sesionFinalizada" => {
                    self.concurrent.remove(&Contexto::SesionActiva);
                },
                "terminarSesion" => {
                    self.base = Contexto::ModoNormal;
                    self.overlay_stack.clear();
                    self.concurrent.remove(&Contexto::SesionActiva);
                },
                "actualizarTimer" => {
                    self.effects.calcular_tiempo_transcurrido(payload_str(payload, "sesion_activa.inicio"));
                },
                _ => {},
            }
        }
    }

    fn dispatch_main(&mut self, event: &str, payload: &serde_json::Value) {
        let _ = payload;
        match self.current_state() {
            Contexto::MenuConfiguracion => {
                match event {
                    "abrirCrearActividad" => {
                        self.overlay_stack.push(Contexto::ModalCrearActividad);
                    },
                    "abrirHistorial" => {
                        self.overlay_stack.push(Contexto::ModalHistorial);
                        self.overlay_stack.push(Contexto::Historial7Dias);
                    },
                    "abrirAcercaDe" => {
                        self.overlay_stack.push(Contexto::ModalAcercaDe);
                    },
                    "abrirReset" => {
                        self.overlay_stack.push(Contexto::ModalReset);
                        self.overlay_stack.push(Contexto::ResetFase1);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalAcercaDe => {
                match event {
                    "cerrar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalComentario => {
                match event {
                    "confirmarInicio" => {
                        self.overlay_stack.pop();
                        self.effects.iniciar_sesion(payload_str(payload, "tipoTareaId"), payload_str(payload, "comentario"), payload_str(payload, "retroactivo"), payload_str(payload, "sustituir"));
                    },
                    "cancelar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalCrearActividad => {
                match event {
                    "guardarNuevaActividad" => {
                        self.overlay_stack.pop();
                        self.effects.crear_actividad(payload_str(payload, "nombre"), payload_str(payload, "color"), payload_str(payload, "permanente"));
                    },
                    "cancelar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalCrearTarea => {
                match event {
                    "guardarNuevaTarea" => {
                        self.overlay_stack.pop();
                        self.effects.crear_tipo_tarea(payload_str(payload, "nombre"), payload_str(payload, "icono"), payload_str(payload, "actividades_seleccionadas"));
                    },
                    "cancelar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalEditarActividad => {
                match event {
                    "guardarEdicionActividad" => {
                        self.overlay_stack.pop();
                        self.effects.actualizar_actividad(payload_str(payload, "actividadId"), payload_str(payload, "nombre"), payload_str(payload, "color"), payload_str(payload, "permanente"));
                    },
                    "cancelar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalEditarTarea => {
                match event {
                    "guardarEdicion" => {
                        self.overlay_stack.pop();
                        self.effects.editar_tipo_tarea(payload_str(payload, "tipoTareaId"), payload_str(payload, "nombre"), payload_str(payload, "icono"));
                    },
                    "cancelar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalHistorial => {
                match event {
                    "iniciar" => {
                        self.replace_top_or_push(Contexto::Historial7Dias);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::Historial7Dias => {
                match event {
                    "cambiarA30Dias" => {
                        self.replace_top_or_push(Contexto::Historial30Dias);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::Historial30Dias => {
                match event {
                    "cambiarA7Dias" => {
                        self.replace_top_or_push(Contexto::Historial7Dias);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalReset => {
                match event {
                    "iniciar" => {
                        self.replace_top_or_push(Contexto::ResetFase1);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ResetFase1 => {
                match event {
                    "avanzarAFase2" => {
                        self.replace_top_or_push(Contexto::ResetFase2);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                        self.overlay_stack.pop();
                    },
                    "exportarCSV" => {
                        self.effects.descargar_csv();
                    },
                    _ => {},
                }
            },
            Contexto::ResetFase2 => {
                match event {
                    "avanzarAFase3" => {
                        self.replace_top_or_push(Contexto::ResetFase3);
                    },
                    "retrocederAFase1" => {
                        self.replace_top_or_push(Contexto::ResetFase1);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ResetFase3 => {
                match event {
                    "ejecutarReset" => {
                        self.overlay_stack.pop();
                        self.overlay_stack.pop();
                        self.effects.reset_datos(payload_str(payload, "actividades_conservar"));
                    },
                    "retrocederAFase2" => {
                        self.replace_top_or_push(Contexto::ResetFase2);
                    },
                    "cerrar" => {
                        self.overlay_stack.pop();
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModalSeleccionActividad => {
                match event {
                    "elegirActividad" => {
                        self.overlay_stack.push(Contexto::ModalComentario);
                    },
                    "cancelar" => {
                        self.overlay_stack.pop();
                    },
                    _ => {},
                }
            },
            Contexto::ModoEdicion => {
                match event {
                    "desactivarEdicion" => {
                        self.base = Contexto::ModoNormal;
                        self.overlay_stack.clear();
                    },
                    "abrirEditarTarea" => {
                        self.overlay_stack.push(Contexto::ModalEditarTarea);
                    },
                    "abrirEditarActividad" => {
                        self.overlay_stack.push(Contexto::ModalEditarActividad);
                    },
                    "abrirCrearTarea" => {
                        self.overlay_stack.push(Contexto::ModalCrearTarea);
                    },
                    "abrirMenuConfiguracion" => {
                        self.overlay_stack.push(Contexto::MenuConfiguracion);
                    },
                    _ => {},
                }
            },
            Contexto::ModoNormal => {
                match event {
                    "activarEdicion" => {
                        self.base = Contexto::ModoEdicion;
                        self.overlay_stack.clear();
                    },
                    "abrirCrearTarea" => {
                        self.overlay_stack.push(Contexto::ModalCrearTarea);
                    },
                    "abrirMenuConfiguracion" => {
                        self.overlay_stack.push(Contexto::MenuConfiguracion);
                    },
                    "iniciarTarea" => {
                        self.concurrent.insert(Contexto::SesionActiva);
                        self.effects.iniciar_sesion(payload_str(payload, "tarea_id"), payload_str(payload, "notas"), payload_str(payload, "minutos_retroactivos"), payload_str(payload, "sustituir"));
                    },
                    "seleccionarTipoTarea" => {
                        self.overlay_stack.push(Contexto::ModalComentario);
                    },
                    "elegirActividad" => {
                        self.overlay_stack.push(Contexto::ModalSeleccionActividad);
                    },
                    "cambiarPestana" => {
                        self.effects.actualizarGridVisible();
                    },
                    _ => {},
                }
            },
            _ => {},
        }
    }

    fn run_on_entry(&self, state: Contexto, payload: &serde_json::Value) {
        let _ = payload;
        match state {
            Contexto::ModalAcercaDe => {
                self.effects.verificar_conexion();
                self.effects.cargar_tiempo_acumulado();
            },
            Contexto::Historial7Dias => {
                self.effects.cargar_historial("dias: 7");
            },
            Contexto::Historial30Dias => {
                self.effects.cargar_historial("dias: 30");
            },
            _ => {},
        }
    }
}

pub fn handle_boton_30dias_tap(ctx: &Contexto, boton_30dias: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::Historial7Dias => {
            println!("[telemetry] context=Historial7Dias, role=boton_30dias, event=tap");
            effects.cambiarA30Dias();
        },
        Contexto::Historial30Dias => {
            println!("[telemetry] context=Historial30Dias, role=boton_30dias, event=tap");
            // ignored
        },
        _ => {},
    }
}

pub fn handle_boton_7dias_tap(ctx: &Contexto, boton_7dias: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::Historial7Dias => {
            println!("[telemetry] context=Historial7Dias, role=boton_7dias, event=tap");
            // ignored
        },
        Contexto::Historial30Dias => {
            println!("[telemetry] context=Historial30Dias, role=boton_7dias, event=tap");
            effects.cambiarA7Dias();
        },
        _ => {},
    }
}

pub fn handle_boton_actividad_tap(ctx: &Contexto, boton_actividad: &Actividad, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalSeleccionActividad => {
            println!("[telemetry] context=ModalSeleccionActividad, role=boton_actividad, event=tap");
            effects.elegirActividad(&boton_actividad.id);
        },
        _ => {},
    }
}

pub fn handle_boton_atras_tap(ctx: &Contexto, boton_atras: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ResetFase2 => {
            println!("[telemetry] context=ResetFase2, role=boton_atras, event=tap");
            effects.retrocederAFase1();
        },
        Contexto::ResetFase3 => {
            println!("[telemetry] context=ResetFase3, role=boton_atras, event=tap");
            effects.retrocederAFase2();
        },
        _ => {},
    }
}

pub fn handle_boton_cancelar_tap(ctx: &Contexto, boton_cancelar: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=boton_cancelar, event=tap");
            effects.cancelar();
        },
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=boton_cancelar, event=tap");
            effects.cancelar();
        },
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=boton_cancelar, event=tap");
            effects.cancelar();
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=boton_cancelar, event=tap");
            effects.cancelar();
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=boton_cancelar, event=tap");
            effects.cancelar();
        },
        Contexto::ModalReset => {
            println!("[telemetry] context=ModalReset, role=boton_cancelar, event=tap");
            effects.cerrar();
        },
        Contexto::ResetFase1 => {
            println!("[telemetry] context=ResetFase1, role=boton_cancelar, event=tap");
            effects.cerrar();
        },
        Contexto::ModalSeleccionActividad => {
            println!("[telemetry] context=ModalSeleccionActividad, role=boton_cancelar, event=tap");
            effects.cancelar();
        },
        _ => {},
    }
}

pub fn handle_boton_cerrar_tap(ctx: &Contexto, boton_cerrar: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalAcercaDe => {
            println!("[telemetry] context=ModalAcercaDe, role=boton_cerrar, event=tap");
            effects.cerrar();
        },
        Contexto::ModalHistorial => {
            println!("[telemetry] context=ModalHistorial, role=boton_cerrar, event=tap");
            effects.cerrar();
        },
        _ => {},
    }
}

pub fn handle_boton_configuracion_tap(ctx: &Contexto, boton_configuracion: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=boton_configuracion, event=tap");
            effects.abrirMenuConfiguracion();
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=boton_configuracion, event=tap");
            effects.abrirMenuConfiguracion();
        },
        _ => {},
    }
}

pub fn handle_boton_confirmar_tap(ctx: &Contexto, boton_confirmar: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=boton_confirmar, event=tap");
            effects.confirmarInicio();
        },
        _ => {},
    }
}

pub fn handle_boton_continuar_tap(ctx: &Contexto, boton_continuar: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ResetFase1 => {
            println!("[telemetry] context=ResetFase1, role=boton_continuar, event=tap");
            effects.avanzarAFase2();
        },
        Contexto::ResetFase2 => {
            println!("[telemetry] context=ResetFase2, role=boton_continuar, event=tap");
            effects.avanzarAFase3();
        },
        _ => {},
    }
}

pub fn handle_boton_edicion_tap(ctx: &Contexto, boton_edicion: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=boton_edicion, event=tap");
            effects.desactivarEdicion();
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=boton_edicion, event=tap");
            effects.activarEdicion();
        },
        _ => {},
    }
}

pub fn handle_boton_ejecutar_tap(ctx: &Contexto, boton_ejecutar: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ResetFase3 => {
            println!("[telemetry] context=ResetFase3, role=boton_ejecutar, event=tap");
            effects.ejecutarReset();
        },
        _ => {},
    }
}

pub fn handle_boton_exportar_csv_tap(ctx: &Contexto, boton_exportar_csv: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ResetFase1 => {
            println!("[telemetry] context=ResetFase1, role=boton_exportar_csv, event=tap");
            effects.exportarCSV();
        },
        _ => {},
    }
}

pub fn handle_boton_guardar_tap(ctx: &Contexto, boton_guardar: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=boton_guardar, event=tap");
            effects.guardarNuevaActividad();
        },
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=boton_guardar, event=tap");
            effects.guardarNuevaTarea();
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=boton_guardar, event=tap");
            effects.guardarEdicionActividad();
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=boton_guardar, event=tap");
            effects.guardarEdicion();
        },
        _ => {},
    }
}

pub fn handle_boton_nuevo_tap(ctx: &Contexto, boton_nuevo: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=boton_nuevo, event=tap");
            effects.abrirCrearTarea();
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=boton_nuevo, event=tap");
            effects.abrirCrearTarea();
        },
        _ => {},
    }
}

pub fn handle_campo_busqueda_icono_cambio(ctx: &Contexto, campo_busqueda_icono: &CampoTexto, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=campo_busqueda_icono, event=cambio");
            effects.filtrarIconosCrear(&campo_busqueda_icono.valor);
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=campo_busqueda_icono, event=cambio");
            effects.filtrarIconos(&campo_busqueda_icono.valor);
        },
        _ => {},
    }
}

pub fn handle_campo_comentario_cambio(ctx: &Contexto, campo_comentario: &CampoTexto, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=campo_comentario, event=cambio");
            effects.actualizarComentario(&campo_comentario.valor);
        },
        _ => {},
    }
}

pub fn handle_campo_confirmacion_cambio(ctx: &Contexto, campo_confirmacion: &CampoTexto, effects: &dyn Effects) {
    match ctx {
        Contexto::ResetFase3 => {
            println!("[telemetry] context=ResetFase3, role=campo_confirmacion, event=cambio");
            effects.actualizarConfirmacion(&campo_confirmacion.valor);
        },
        _ => {},
    }
}

pub fn handle_campo_nombre_cambio(ctx: &Contexto, campo_nombre: &CampoTexto, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=campo_nombre, event=cambio");
            effects.actualizarNombreNuevaActividad(&campo_nombre.valor);
        },
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=campo_nombre, event=cambio");
            effects.actualizarNuevoNombre(&campo_nombre.valor);
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=campo_nombre, event=cambio");
            effects.actualizarNombreActividad(&campo_nombre.valor);
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=campo_nombre, event=cambio");
            effects.actualizarNombre(&campo_nombre.valor);
        },
        _ => {},
    }
}

pub fn handle_campo_retroactivo_cambio(ctx: &Contexto, campo_retroactivo: &CampoNumerico, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=campo_retroactivo, event=cambio");
            effects.actualizarRetroactivo(&campo_retroactivo.valor);
        },
        _ => {},
    }
}

pub fn handle_checkbox_actividad_cambio(ctx: &Contexto, checkbox_actividad: &OpcionActividad, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=checkbox_actividad, event=cambio");
            effects.toggleActividadPermitida(&checkbox_actividad.id, &checkbox_actividad.marcado);
        },
        Contexto::ResetFase2 => {
            println!("[telemetry] context=ResetFase2, role=checkbox_actividad, event=cambio");
            effects.toggleConservar(&checkbox_actividad.id, &checkbox_actividad.marcado);
        },
        _ => {},
    }
}

pub fn handle_checkbox_permanente_cambio(ctx: &Contexto, checkbox_permanente: &Checkbox, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=checkbox_permanente, event=cambio");
            effects.marcarPermanenteNueva(&checkbox_permanente.marcado);
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=checkbox_permanente, event=cambio");
            effects.marcarPermanente(&checkbox_permanente.marcado);
        },
        _ => {},
    }
}

pub fn handle_checkbox_sustituir_cambio(ctx: &Contexto, checkbox_sustituir: &Checkbox, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=checkbox_sustituir, event=cambio");
            effects.marcarSustituir(&checkbox_sustituir.marcado);
        },
        _ => {},
    }
}

pub fn handle_display_timer_tap(ctx: &Contexto, display_timer: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::SesionActiva => {
            println!("[telemetry] context=SesionActiva, role=display_timer, event=tap");
            // ignored
        },
        _ => {},
    }
}

pub fn handle_item_acerca_de_tap(ctx: &Contexto, item_acerca_de: &ItemMenu, effects: &dyn Effects) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_acerca_de, event=tap");
            effects.abrirAcercaDe();
        },
        _ => {},
    }
}

pub fn handle_item_historial_tap(ctx: &Contexto, item_historial: &ItemMenu, effects: &dyn Effects) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_historial, event=tap");
            effects.abrirHistorial();
        },
        _ => {},
    }
}

pub fn handle_item_nueva_actividad_tap(ctx: &Contexto, item_nueva_actividad: &ItemMenu, effects: &dyn Effects) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_nueva_actividad, event=tap");
            effects.abrirCrearActividad();
        },
        _ => {},
    }
}

pub fn handle_item_reset_tap(ctx: &Contexto, item_reset: &ItemMenu, effects: &dyn Effects) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_reset, event=tap");
            effects.abrirReset();
        },
        _ => {},
    }
}

pub fn handle_overlay_tap(ctx: &Contexto, overlay: &Boton, effects: &dyn Effects) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=overlay, event=tap");
            effects.cerrar();
        },
        _ => {},
    }
}

pub fn handle_pestana_actividad_tap(ctx: &Contexto, pestana_actividad: &Actividad, effects: &dyn Effects) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=pestana_actividad, event=tap");
            effects.abrirEditarActividad(&pestana_actividad.id);
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=pestana_actividad, event=tap");
            effects.cambiarPestana(&pestana_actividad.id);
        },
        _ => {},
    }
}

pub fn handle_pestana_frecuentes_tap(ctx: &Contexto, pestana_frecuentes: &Pestana, effects: &dyn Effects) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=pestana_frecuentes, event=tap");
            // ignored
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=pestana_frecuentes, event=tap");
            effects.cambiarPestana("'frecuentes'");
        },
        _ => {},
    }
}

pub fn handle_selector_color_seleccion(ctx: &Contexto, selector_color: &SelectorColor, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=selector_color, event=seleccion");
            effects.seleccionarColorNuevo(&selector_color.seleccionado);
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=selector_color, event=seleccion");
            effects.seleccionarColor(&selector_color.seleccionado);
        },
        _ => {},
    }
}

pub fn handle_selector_icono_seleccion(ctx: &Contexto, selector_icono: &SelectorIcono, effects: &dyn Effects) {
    match ctx {
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=selector_icono, event=seleccion");
            effects.seleccionarIconoNuevo(&selector_icono.seleccionado);
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=selector_icono, event=seleccion");
            effects.seleccionarIcono(&selector_icono.seleccionado);
        },
        _ => {},
    }
}

pub fn handle_tarjeta_tarea_tap(ctx: &Contexto, tarjeta_tarea: &Tarea, effects: &dyn Effects) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=tarjeta_tarea, event=tap");
            effects.abrirEditarTarea(&tarjeta_tarea.tipoId);
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=tarjeta_tarea, event=tap");
            effects.iniciarTarea(&tarjeta_tarea.tareaId);
        },
        _ => {},
    }
}

pub fn handle_tarjeta_tipo_tap(ctx: &Contexto, tarjeta_tipo: &TipoTarea, effects: &dyn Effects) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=tarjeta_tipo, event=tap");
            effects.abrirEditarTarea(&tarjeta_tipo.tipoId);
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=tarjeta_tipo, event=tap");
            effects.seleccionarTipoTarea(&tarjeta_tipo.tipoId);
        },
        _ => {},
    }
}

