// Auto-generated by Trenza DSL Compiler
// Compiler Profile: pre
// Concurrency Mode: composite

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Contexto {
    MenuConfiguracion,
    ModalAcercaDe,
    ModalComentario,
    ModalCrearActividad,
    ModalCrearTarea,
    ModalEditarActividad,
    ModalEditarTarea,
    ModalHistorial,
    Historial7Dias,
    Historial30Dias,
    ModalReset,
    ResetFase1,
    ResetFase2,
    ResetFase3,
    ModalSeleccionActividad,
    ModoEdicion,
    ModoNormal,
    SesionActiva,
}

use std::collections::HashSet;

pub struct System {
    pub state: Contexto,
    pub concurrent_states: HashSet<Contexto>,
}

impl System {
    pub fn new(initial: Contexto) -> Self {
        let mut concurrent_states = HashSet::new();
        concurrent_states.insert(Contexto::SesionActiva);
        Self { state: initial, concurrent_states }
    }

    pub fn handle_event(&mut self, event: &str) {
        // Evaluate concurrent states sequentially (Composite Mode)
        if self.concurrent_states.contains(&Contexto::SesionActiva) {
            // In a full composite synthesis, we evaluate SesionActiva logic here
        }

        // Evaluate main state
        match self.state {
            Contexto::MenuConfiguracion => {
                match event {
                    "abrirCrearActividad" => self.state = Contexto::ModalCrearActividad,
                    "abrirHistorial" => self.state = Contexto::ModalHistorial,
                    "abrirAcercaDe" => self.state = Contexto::ModalAcercaDe,
                    "abrirReset" => self.state = Contexto::ModalReset,
                    "cerrar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModalAcercaDe => {
                match event {
                    "cerrar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModalComentario => {
                match event {
                    "confirmarInicio" => self.state = Contexto::[cerrar_overlay],
                    "cancelar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModalCrearActividad => {
                match event {
                    "guardarNuevaActividad" => self.state = Contexto::[cerrar_overlay],
                    "cancelar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModalCrearTarea => {
                match event {
                    "guardarNuevaTarea" => self.state = Contexto::[cerrar_overlay],
                    "cancelar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModalEditarActividad => {
                match event {
                    "guardarEdicionActividad" => self.state = Contexto::[cerrar_overlay],
                    "cancelar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModalEditarTarea => {
                match event {
                    "guardarEdicion" => self.state = Contexto::[cerrar_overlay],
                    "cancelar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModalHistorial => {
                match event {
                    "cerrar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::Historial7Dias => {
                match event {
                    "cambiarA30Dias" => self.state = Contexto::Historial30Dias,
                    "cerrar" => self.state = Contexto::ModalHistorial,
                    _ => {},
                }
            },
            Contexto::Historial30Dias => {
                match event {
                    "cambiarA7Dias" => self.state = Contexto::Historial7Dias,
                    "cerrar" => self.state = Contexto::ModalHistorial,
                    _ => {},
                }
            },
            Contexto::ModalReset => {
                match event {
                    "cerrar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ResetFase1 => {
                match event {
                    "avanzarAFase2" => self.state = Contexto::ResetFase2,
                    "cerrar" => self.state = Contexto::ModalReset,
                    _ => {},
                }
            },
            Contexto::ResetFase2 => {
                match event {
                    "avanzarAFase3" => self.state = Contexto::ResetFase3,
                    "retrocederAFase1" => self.state = Contexto::ResetFase1,
                    _ => {},
                }
            },
            Contexto::ResetFase3 => {
                match event {
                    "ejecutarReset" => self.state = Contexto::[cerrar_overlay],
                    "retrocederAFase2" => self.state = Contexto::ResetFase2,
                    _ => {},
                }
            },
            Contexto::ModalSeleccionActividad => {
                match event {
                    "elegirActividad" => self.state = Contexto::ModalComentario,
                    "cancelar" => self.state = Contexto::[cerrar_overlay],
                    _ => {},
                }
            },
            Contexto::ModoEdicion => {
                match event {
                    "desactivarEdicion" => self.state = Contexto::ModoNormal,
                    "abrirEditarTarea" => self.state = Contexto::ModalEditarTarea,
                    "abrirEditarActividad" => self.state = Contexto::ModalEditarActividad,
                    "abrirCrearTarea" => self.state = Contexto::ModalCrearTarea,
                    "abrirMenuConfiguracion" => self.state = Contexto::MenuConfiguracion,
                    _ => {},
                }
            },
            Contexto::ModoNormal => {
                match event {
                    "activarEdicion" => self.state = Contexto::ModoEdicion,
                    "abrirCrearTarea" => self.state = Contexto::ModalCrearTarea,
                    "abrirMenuConfiguracion" => self.state = Contexto::MenuConfiguracion,
                    "seleccionarTipoTarea" => self.state = Contexto::ModalComentario,
                    _ => {},
                }
            },
            Contexto::SesionActiva => {
                match event {
                    "sesionFinalizada" => self.state = Contexto::[deactivate],
                    _ => {},
                }
            },
        }
    }
}

pub fn handle_boton_30dias_tap(ctx: &Contexto) {
    match ctx {
        Contexto::Historial7Dias => {
            println!("[telemetry] context=Historial7Dias, role=boton_30dias, event=tap");
            // execute cambiarA30Dias
        },
        Contexto::Historial30Dias => {
            println!("[telemetry] context=Historial30Dias, role=boton_30dias, event=tap");
            // ignored
        },
    }
}

pub fn handle_boton_7dias_tap(ctx: &Contexto) {
    match ctx {
        Contexto::Historial7Dias => {
            println!("[telemetry] context=Historial7Dias, role=boton_7dias, event=tap");
            // ignored
        },
        Contexto::Historial30Dias => {
            println!("[telemetry] context=Historial30Dias, role=boton_7dias, event=tap");
            // execute cambiarA7Dias
        },
    }
}

pub fn handle_boton_actividad_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModalSeleccionActividad => {
            println!("[telemetry] context=ModalSeleccionActividad, role=boton_actividad, event=tap");
            // execute elegirActividad
        },
    }
}

pub fn handle_boton_atras_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ResetFase2 => {
            println!("[telemetry] context=ResetFase2, role=boton_atras, event=tap");
            // execute retrocederAFase1
        },
        Contexto::ResetFase3 => {
            println!("[telemetry] context=ResetFase3, role=boton_atras, event=tap");
            // execute retrocederAFase2
        },
    }
}

pub fn handle_boton_cancelar_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=boton_cancelar, event=tap");
            // execute cancelar
        },
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=boton_cancelar, event=tap");
            // execute cancelar
        },
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=boton_cancelar, event=tap");
            // execute cancelar
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=boton_cancelar, event=tap");
            // execute cancelar
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=boton_cancelar, event=tap");
            // execute cancelar
        },
        Contexto::ModalReset => {
            println!("[telemetry] context=ModalReset, role=boton_cancelar, event=tap");
            // execute cerrar
        },
        Contexto::ResetFase1 => {
            println!("[telemetry] context=ResetFase1, role=boton_cancelar, event=tap");
            // execute cerrar
        },
        Contexto::ModalSeleccionActividad => {
            println!("[telemetry] context=ModalSeleccionActividad, role=boton_cancelar, event=tap");
            // execute cancelar
        },
    }
}

pub fn handle_boton_cerrar_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModalAcercaDe => {
            println!("[telemetry] context=ModalAcercaDe, role=boton_cerrar, event=tap");
            // execute cerrar
        },
        Contexto::ModalHistorial => {
            println!("[telemetry] context=ModalHistorial, role=boton_cerrar, event=tap");
            // execute cerrar
        },
    }
}

pub fn handle_boton_configuracion_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=boton_configuracion, event=tap");
            // execute abrirMenuConfiguracion
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=boton_configuracion, event=tap");
            // execute abrirMenuConfiguracion
        },
    }
}

pub fn handle_boton_confirmar_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=boton_confirmar, event=tap");
            // execute confirmarInicio
        },
    }
}

pub fn handle_boton_continuar_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ResetFase1 => {
            println!("[telemetry] context=ResetFase1, role=boton_continuar, event=tap");
            // execute avanzarAFase2
        },
        Contexto::ResetFase2 => {
            println!("[telemetry] context=ResetFase2, role=boton_continuar, event=tap");
            // execute avanzarAFase3
        },
    }
}

pub fn handle_boton_edicion_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=boton_edicion, event=tap");
            // execute desactivarEdicion
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=boton_edicion, event=tap");
            // execute activarEdicion
        },
    }
}

pub fn handle_boton_ejecutar_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ResetFase3 => {
            println!("[telemetry] context=ResetFase3, role=boton_ejecutar, event=tap");
            // execute ejecutarReset
        },
    }
}

pub fn handle_boton_exportar_csv_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ResetFase1 => {
            println!("[telemetry] context=ResetFase1, role=boton_exportar_csv, event=tap");
            // execute exportarCSV
        },
    }
}

pub fn handle_boton_guardar_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=boton_guardar, event=tap");
            // execute guardarNuevaActividad
        },
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=boton_guardar, event=tap");
            // execute guardarNuevaTarea
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=boton_guardar, event=tap");
            // execute guardarEdicionActividad
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=boton_guardar, event=tap");
            // execute guardarEdicion
        },
    }
}

pub fn handle_boton_nuevo_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=boton_nuevo, event=tap");
            // execute abrirCrearTarea
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=boton_nuevo, event=tap");
            // execute abrirCrearTarea
        },
    }
}

pub fn handle_campo_busqueda_icono_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=campo_busqueda_icono, event=cambio");
            // execute filtrarIconosCrear
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=campo_busqueda_icono, event=cambio");
            // execute filtrarIconos
        },
    }
}

pub fn handle_campo_comentario_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=campo_comentario, event=cambio");
            // execute actualizarComentario
        },
    }
}

pub fn handle_campo_confirmacion_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::ResetFase3 => {
            println!("[telemetry] context=ResetFase3, role=campo_confirmacion, event=cambio");
            // execute actualizarConfirmacion
        },
    }
}

pub fn handle_campo_nombre_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=campo_nombre, event=cambio");
            // execute actualizarNombreNuevaActividad
        },
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=campo_nombre, event=cambio");
            // execute actualizarNuevoNombre
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=campo_nombre, event=cambio");
            // execute actualizarNombreActividad
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=campo_nombre, event=cambio");
            // execute actualizarNombre
        },
    }
}

pub fn handle_campo_retroactivo_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::ModalComentario => {
            println!("[telemetry] context=ModalComentario, role=campo_retroactivo, event=cambio");
            // execute actualizarRetroactivo
        },
    }
}

pub fn handle_checkbox_actividad_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=checkbox_actividad, event=cambio");
            // execute toggleActividadPermitida
        },
        Contexto::ResetFase2 => {
            println!("[telemetry] context=ResetFase2, role=checkbox_actividad, event=cambio");
            // execute toggleConservar
        },
    }
}

pub fn handle_checkbox_permanente_cambio(ctx: &Contexto) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=checkbox_permanente, event=cambio");
            // execute marcarPermanenteNueva
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=checkbox_permanente, event=cambio");
            // execute marcarPermanente
        },
    }
}

pub fn handle_display_timer_tap(ctx: &Contexto) {
    match ctx {
        Contexto::SesionActiva => {
            println!("[telemetry] context=SesionActiva, role=display_timer, event=tap");
            // ignored
        },
    }
}

pub fn handle_item_acerca_de_tap(ctx: &Contexto) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_acerca_de, event=tap");
            // execute abrirAcercaDe
        },
    }
}

pub fn handle_item_historial_tap(ctx: &Contexto) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_historial, event=tap");
            // execute abrirHistorial
        },
    }
}

pub fn handle_item_nueva_actividad_tap(ctx: &Contexto) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_nueva_actividad, event=tap");
            // execute abrirCrearActividad
        },
    }
}

pub fn handle_item_reset_tap(ctx: &Contexto) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=item_reset, event=tap");
            // execute abrirReset
        },
    }
}

pub fn handle_overlay_tap(ctx: &Contexto) {
    match ctx {
        Contexto::MenuConfiguracion => {
            println!("[telemetry] context=MenuConfiguracion, role=overlay, event=tap");
            // execute cerrar
        },
    }
}

pub fn handle_pestana_actividad_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=pestana_actividad, event=tap");
            // execute abrirEditarActividad
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=pestana_actividad, event=tap");
            // execute cambiarPestana
        },
    }
}

pub fn handle_pestana_frecuentes_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=pestana_frecuentes, event=tap");
            // ignored
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=pestana_frecuentes, event=tap");
            // execute cambiarPestana
        },
    }
}

pub fn handle_selector_color_seleccion(ctx: &Contexto) {
    match ctx {
        Contexto::ModalCrearActividad => {
            println!("[telemetry] context=ModalCrearActividad, role=selector_color, event=seleccion");
            // execute seleccionarColorNuevo
        },
        Contexto::ModalEditarActividad => {
            println!("[telemetry] context=ModalEditarActividad, role=selector_color, event=seleccion");
            // execute seleccionarColor
        },
    }
}

pub fn handle_selector_icono_seleccion(ctx: &Contexto) {
    match ctx {
        Contexto::ModalCrearTarea => {
            println!("[telemetry] context=ModalCrearTarea, role=selector_icono, event=seleccion");
            // execute seleccionarIconoNuevo
        },
        Contexto::ModalEditarTarea => {
            println!("[telemetry] context=ModalEditarTarea, role=selector_icono, event=seleccion");
            // execute seleccionarIcono
        },
    }
}

pub fn handle_tarjeta_tarea_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=tarjeta_tarea, event=tap");
            // execute abrirEditarTarea
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=tarjeta_tarea, event=tap");
            // execute iniciarTarea
        },
    }
}

pub fn handle_tarjeta_tipo_tap(ctx: &Contexto) {
    match ctx {
        Contexto::ModoEdicion => {
            println!("[telemetry] context=ModoEdicion, role=tarjeta_tipo, event=tap");
            // execute abrirEditarTarea
        },
        Contexto::ModoNormal => {
            println!("[telemetry] context=ModoNormal, role=tarjeta_tipo, event=tap");
            // execute seleccionarTipoTarea
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transition_MenuConfiguracion_on_abrirCrearActividad() {
        let mut sys = System::new(Contexto::MenuConfiguracion);
        sys.handle_event("abrirCrearActividad");
        assert_eq!(sys.state, Contexto::ModalCrearActividad);
    }

    #[test]
    fn test_transition_MenuConfiguracion_on_abrirHistorial() {
        let mut sys = System::new(Contexto::MenuConfiguracion);
        sys.handle_event("abrirHistorial");
        assert_eq!(sys.state, Contexto::ModalHistorial);
    }

    #[test]
    fn test_transition_MenuConfiguracion_on_abrirAcercaDe() {
        let mut sys = System::new(Contexto::MenuConfiguracion);
        sys.handle_event("abrirAcercaDe");
        assert_eq!(sys.state, Contexto::ModalAcercaDe);
    }

    #[test]
    fn test_transition_MenuConfiguracion_on_abrirReset() {
        let mut sys = System::new(Contexto::MenuConfiguracion);
        sys.handle_event("abrirReset");
        assert_eq!(sys.state, Contexto::ModalReset);
    }

    #[test]
    fn test_transition_MenuConfiguracion_on_cerrar() {
        let mut sys = System::new(Contexto::MenuConfiguracion);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalAcercaDe_on_cerrar() {
        let mut sys = System::new(Contexto::ModalAcercaDe);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalComentario_on_confirmarInicio() {
        let mut sys = System::new(Contexto::ModalComentario);
        sys.handle_event("confirmarInicio");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalComentario_on_cancelar() {
        let mut sys = System::new(Contexto::ModalComentario);
        sys.handle_event("cancelar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalCrearActividad_on_guardarNuevaActividad() {
        let mut sys = System::new(Contexto::ModalCrearActividad);
        sys.handle_event("guardarNuevaActividad");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalCrearActividad_on_cancelar() {
        let mut sys = System::new(Contexto::ModalCrearActividad);
        sys.handle_event("cancelar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalCrearTarea_on_guardarNuevaTarea() {
        let mut sys = System::new(Contexto::ModalCrearTarea);
        sys.handle_event("guardarNuevaTarea");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalCrearTarea_on_cancelar() {
        let mut sys = System::new(Contexto::ModalCrearTarea);
        sys.handle_event("cancelar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalEditarActividad_on_guardarEdicionActividad() {
        let mut sys = System::new(Contexto::ModalEditarActividad);
        sys.handle_event("guardarEdicionActividad");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalEditarActividad_on_cancelar() {
        let mut sys = System::new(Contexto::ModalEditarActividad);
        sys.handle_event("cancelar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalEditarTarea_on_guardarEdicion() {
        let mut sys = System::new(Contexto::ModalEditarTarea);
        sys.handle_event("guardarEdicion");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalEditarTarea_on_cancelar() {
        let mut sys = System::new(Contexto::ModalEditarTarea);
        sys.handle_event("cancelar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModalHistorial_on_cerrar() {
        let mut sys = System::new(Contexto::ModalHistorial);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_Historial7Dias_on_cambiarA30Dias() {
        let mut sys = System::new(Contexto::Historial7Dias);
        sys.handle_event("cambiarA30Dias");
        assert_eq!(sys.state, Contexto::Historial30Dias);
    }

    #[test]
    fn test_transition_Historial7Dias_on_cerrar() {
        let mut sys = System::new(Contexto::Historial7Dias);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::ModalHistorial);
    }

    #[test]
    fn test_transition_Historial30Dias_on_cambiarA7Dias() {
        let mut sys = System::new(Contexto::Historial30Dias);
        sys.handle_event("cambiarA7Dias");
        assert_eq!(sys.state, Contexto::Historial7Dias);
    }

    #[test]
    fn test_transition_Historial30Dias_on_cerrar() {
        let mut sys = System::new(Contexto::Historial30Dias);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::ModalHistorial);
    }

    #[test]
    fn test_transition_ModalReset_on_cerrar() {
        let mut sys = System::new(Contexto::ModalReset);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ResetFase1_on_avanzarAFase2() {
        let mut sys = System::new(Contexto::ResetFase1);
        sys.handle_event("avanzarAFase2");
        assert_eq!(sys.state, Contexto::ResetFase2);
    }

    #[test]
    fn test_transition_ResetFase1_on_cerrar() {
        let mut sys = System::new(Contexto::ResetFase1);
        sys.handle_event("cerrar");
        assert_eq!(sys.state, Contexto::ModalReset);
    }

    #[test]
    fn test_transition_ResetFase2_on_avanzarAFase3() {
        let mut sys = System::new(Contexto::ResetFase2);
        sys.handle_event("avanzarAFase3");
        assert_eq!(sys.state, Contexto::ResetFase3);
    }

    #[test]
    fn test_transition_ResetFase2_on_retrocederAFase1() {
        let mut sys = System::new(Contexto::ResetFase2);
        sys.handle_event("retrocederAFase1");
        assert_eq!(sys.state, Contexto::ResetFase1);
    }

    #[test]
    fn test_transition_ResetFase3_on_ejecutarReset() {
        let mut sys = System::new(Contexto::ResetFase3);
        sys.handle_event("ejecutarReset");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ResetFase3_on_retrocederAFase2() {
        let mut sys = System::new(Contexto::ResetFase3);
        sys.handle_event("retrocederAFase2");
        assert_eq!(sys.state, Contexto::ResetFase2);
    }

    #[test]
    fn test_transition_ModalSeleccionActividad_on_elegirActividad() {
        let mut sys = System::new(Contexto::ModalSeleccionActividad);
        sys.handle_event("elegirActividad");
        assert_eq!(sys.state, Contexto::ModalComentario);
    }

    #[test]
    fn test_transition_ModalSeleccionActividad_on_cancelar() {
        let mut sys = System::new(Contexto::ModalSeleccionActividad);
        sys.handle_event("cancelar");
        assert_eq!(sys.state, Contexto::[cerrar_overlay]);
    }

    #[test]
    fn test_transition_ModoEdicion_on_desactivarEdicion() {
        let mut sys = System::new(Contexto::ModoEdicion);
        sys.handle_event("desactivarEdicion");
        assert_eq!(sys.state, Contexto::ModoNormal);
    }

    #[test]
    fn test_transition_ModoEdicion_on_abrirEditarTarea() {
        let mut sys = System::new(Contexto::ModoEdicion);
        sys.handle_event("abrirEditarTarea");
        assert_eq!(sys.state, Contexto::ModalEditarTarea);
    }

    #[test]
    fn test_transition_ModoEdicion_on_abrirEditarActividad() {
        let mut sys = System::new(Contexto::ModoEdicion);
        sys.handle_event("abrirEditarActividad");
        assert_eq!(sys.state, Contexto::ModalEditarActividad);
    }

    #[test]
    fn test_transition_ModoEdicion_on_abrirCrearTarea() {
        let mut sys = System::new(Contexto::ModoEdicion);
        sys.handle_event("abrirCrearTarea");
        assert_eq!(sys.state, Contexto::ModalCrearTarea);
    }

    #[test]
    fn test_transition_ModoEdicion_on_abrirMenuConfiguracion() {
        let mut sys = System::new(Contexto::ModoEdicion);
        sys.handle_event("abrirMenuConfiguracion");
        assert_eq!(sys.state, Contexto::MenuConfiguracion);
    }

    #[test]
    fn test_transition_ModoNormal_on_activarEdicion() {
        let mut sys = System::new(Contexto::ModoNormal);
        sys.handle_event("activarEdicion");
        assert_eq!(sys.state, Contexto::ModoEdicion);
    }

    #[test]
    fn test_transition_ModoNormal_on_abrirCrearTarea() {
        let mut sys = System::new(Contexto::ModoNormal);
        sys.handle_event("abrirCrearTarea");
        assert_eq!(sys.state, Contexto::ModalCrearTarea);
    }

    #[test]
    fn test_transition_ModoNormal_on_abrirMenuConfiguracion() {
        let mut sys = System::new(Contexto::ModoNormal);
        sys.handle_event("abrirMenuConfiguracion");
        assert_eq!(sys.state, Contexto::MenuConfiguracion);
    }

    #[test]
    fn test_transition_ModoNormal_on_seleccionarTipoTarea() {
        let mut sys = System::new(Contexto::ModoNormal);
        sys.handle_event("seleccionarTipoTarea");
        assert_eq!(sys.state, Contexto::ModalComentario);
    }

    #[test]
    fn test_transition_SesionActiva_on_sesionFinalizada() {
        let mut sys = System::new(Contexto::SesionActiva);
        sys.handle_event("sesionFinalizada");
        assert_eq!(sys.state, Contexto::[deactivate]);
    }

}
